### ISSUE TITLE
code inside .md file not auto rendering in github or gitlab

### ISSUE THREAD

**Issue by razakpm** [plantuml-stdlib/C4-PlantUML#109]
Earlier I put c4 plantuml code inside "README.md" and the diagram was auto rendering , but now it is not working.

To verify "copy code from a .puml file (from examples in this repo) and paste inside a readme.md file ,
 just add 
```
```plantuml as first line
and ``` as last line.
``` 
it will show the below error, earlier it was working 

![image](https://user-images.githubusercontent.com/1684932/104594654-7a7d1400-5697-11eb-9482-4e7a780316fd.png)

**Comment by Potherca** [comment]
I think your problem might be because of using `master`. 

It is advised to use URLs like `https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/release/1-0/Context.puml` or `https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4_Context.puml` rather than `master`

Could you try that to see if it resolves things?

**Comment by kirchsth** [comment]
It could be the same problem like in  #99 (instead of asciidoc is it in your case github,... )  and an older plantUML version is referenced and therefore the new version is not working anymore (details see #99). If this is the case you have to request on github/gitlab side that they are upgrading to the newer plantuml version.
(or you can follow Potherca's workaround and continue with the older C4 version)
