### ISSUE TITLE
SystemDb and SystemDb_Ext are missing

### ISSUE THREAD

**Issue by anorm** [plantuml-stdlib/C4-PlantUML#113]
We used to have `SystemDb` and `SystemDb_Ext` in the `C4/C4_Context` library, these are now gone.

While I agree you wouldn't typically design a system landscape with a database at the system level, designs exist that have this and removing the possibility to express this in the library makes us unable to draw this.

Please add `SystemDb` and `SystemDb_Ext` macros back.

**Comment by Potherca** [comment]
Hi, thank you for taking the time to report this!

`SystemDb` and `SystemDb_Ext` were added in December 2018  as part of 754721b740a3296345463cec32bfce08be0cb548, (together with `ContainerDb` and `ComponentDb`) and are part of v1.

They have been removed November 2020 in a9303abebc035105af8e77eaea873a5375ab1b2d and are no longer part of v2.

I don't know _why_ they have been removed, maybe @adrianvlupu can elaborate?

**Comment by cabello** [comment]
To provide some context on why I asked about this: we have some diagrams using `includeurl https://raw.github...` and they became invalid and stopped rendering because we were pointing to this repo, main branch. The change was breaking and I could find more information on it.

I have since forked the repo (just for stability, I am grateful for this being put together and maintained  🙇 ), alternatively I could point to a specific commit 🤔 , unsure what's the best way to proceed. Ideally I don't want to maintain a fork that is nothing but a frozen point in time, maybe pointing to a Semantic Versioned tag?
`https://raw....#v2` to get latest v2 that is not breaking? 🤔

**Comment by Potherca** [comment]
@cabello Instead of using an URL like `https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml` (from `master`) you should probably use the `1-0` branch: [`https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/release/1-0/C4.puml`](https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/release/1-0/C4.puml) or the `v1.0.0` tag: [`https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4.puml`](https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4.puml)

**Comment by anorm** [comment]
My designs broke while using the stdlib embedded in plantuml:
```
@startuml
!include <C4/C4_Context>
System(foo, "Foo")
SystemDb(bar, "Bar")
Rel(foo, bar, "Baz")
@enduml
```

Breaking stdlib API is bad practice in my opinion. Also, adding these macros back won't do any harm.

**Comment by Potherca** [comment]
> Breaking stdlib API is bad practice

I think all involved will agree with that statement. What complicates matters, is that this project was originally meant to be used stand-alone, so you would have control over which version you use. 

With this repo being include in PlantUML, things become more complex.

> Also, adding these macros back won't do any harm.

Until we hear from @adrianvlupu, I can't really comment on that. Also, adding them back _here_ won't resolve the issue... the changes will still have to be added (and released) over at [PlantUML std-lib](https://github.com/plantuml/plantuml-stdlib).

_Technically_ this issue even belongs there.

However, since the chance of an issue like this happening again is rather large, it would be good if we also come up with a way to prevent things like this from happening in the future (here as well as for other std-lib repos).

**Comment by anorm** [comment]
> Until we hear from @adrianvlupu, I can't really comment on that. Also, adding them back here won't resolve the issue... the changes will still have to be added (and released) over at PlantUML std-lib.

I was under the impression that _this_ was the stdlib repository. The stdlib bundled within the plantuml release (the one used when I `!include <C4/C4_Context>` contains the breaking change. Should I post an issue in the other repository also/instead?

**Comment by Potherca** [comment]
> I was under the impression that this was the stdlib repository.

This is where the originating code comes from/is maintained. We are not an official part of PlantUML.

Allow me te explain with a diagram:

![](http://www.plantuml.com/plantuml/png/ZPDHQzim4CVVzIcElAmBE6jIjokbX8wKReEk6Inx3h9yIaLadP4LbdJqkq-sboXERLm_67JtkxzEVvtk2iUjssIQ5MjbScvv1dyP-EzH6LpiSWIoxfbO5Rj7oJVQFP1nlzGBmkISrOalrjAVkh3wPgJ9GgAvM1zYYsSbrWQB0YQZyqEqr0g5BSNXgxOSNpTZRgSH4jBf8VpAwlyhOnQ5usRbYS5FpOtx_UCHphugzssJmDokk545TuhCnm7m0l8IyLOioQx-jsGezRNx19nPpEa4BaD71v2-5RHGk5IhvEHWt3ebkN0m4774a-t8rsuhDR_e9bCy8ltYzAGjdKRr_iSDrv6ETcTnYOXuMQ-RRKkbqHEZt0kN68xRqiiPPJaPD2w0amxGEAuCsW1UT8AuFTABMx5xp3NjiiREb-tapl1CYO1TDR0FDVZzwM5UPJ_tpDIfszsZLGDl1ciMHs4kmrM9E5nJ-nN8CUktNqvOl_NoWlNPBcFs3ilb9UkpMru56mqv14Sva6myl8guBTGBtaokftCfbL1SmzwcsqzbQihGfAK2Qme5cviom-7JV34SmZlaQWc8ecdZnTn0ib7QWRIKiVtzHDfJXqVZ6K6vmXGSiJklw4_q3m00)

> Should I post an issue in the other repository also/instead?

That is not necessary. We've got an update coming up in https://github.com/plantuml/plantuml-stdlib/issues/31, I'll make sure this fix is also included. It is also one of those things we are still in the process of figuring out how to best do, as such a fix would eventually have to be present in both repos anyway...

**Comment by adrianvlupu** [comment]
Hi, the reason for removing them from my initial fork was because I never used them and imagined no one else would. When having stuff like firebase showing up in diagrams, I usually added them as a container.
I thought the same was true for components, but figured that a piece of software could have some component that behaves like a queue/storage/etc and a visual representation could be helpful.

Contradictory stuff I know, but I think a lot more people use the component version. 
I think I deleted them after a pull request that added the queue shape, questioning if a queue can be a system and noticing the codebase was getting bigger and bigger and starting to receive errors when using the online plantuml server and local includes.

Regardless, if people have a use case for them I will create a PR to bring them back.

Sorry for breaking your diagrams

**Comment by Potherca** [comment]
@adrianvlupu Thank you for the clarification! If you are short on time or energy, let me know. In such a case I can set up the MR. :+1: 

@cabello and @anorm Thank you for your patience. It looks like the missing items will be added back, as request, without any omission. As soon as this (and some other fixes in other MRs) has been merged into master, I'll run a release and follow up at [plantuml/plantuml-stdlib](https://github.com/plantuml/plantuml-stdlib) to get the changes merged into the official release <abbr title="as soon as possible">ASAP</abbr>.

**Comment by cabello** [comment]
It's fine, I was just curious, I like the idea of pinning to a version tag and the project using semantic versioning so I can check the changelog when moving from V1 to V2.

I appreciate the discussion here.

My personal next steps are:
* move away from using my fork
* point to tag v2, given I fixed all SystemDb and SystemDb_Ext from my digrams
* watch this project for new release

:D

**Comment by anorm** [comment]
If anyone else is having trouble with this, I can share what my temporary solution is:

In all of my designs, I include an extra `util.puml` file with some extra helpers. I've added a section which compensates for the inconsistencies.

```
!if (%version() >= "1.2021.00")
!define PersonIcon(id, name) Person(id, name)
!define PersonIcon(id, name, desc) Person(id, name, desc)
!else
!define PersonIcon(id, name) Person(id, "<&person,scale=3>\n==name")
!define PersonIcon(id, name, desc) Person(id, "<&person,scale=3>\n==name", desc)
!endif

!if ((%version() == "1.2021.00") || (%version() == "1.2021.01"))
skinparam database<<system>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $SYSTEM_BG_COLOR
    BorderColor #3C7FC0
}

skinparam database<<external_system>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $EXTERNAL_SYSTEM_BG_COLOR
    BorderColor #8A8A8A
}
!define SystemDb(e_alias, e_label) database "==e_label" <<system>> as e_alias
!define SystemDb(e_alias, e_label, e_descr) database "==e_label\n\n e_descr" <<system>> as e_alias
!define SystemDb_Ext(e_alias, e_label) database "==e_label" <<external_system>> as e_alias
!define SystemDb_Ext(e_alias, e_label, e_descr) database "==e_label\n\n e_descr" <<external_system>> as e_alias
!endif
```
