### ISSUE TITLE
List of available icons in repository

### ISSUE THREAD

**Issue by faocrates** [plantuml-stdlib/C4-PlantUML#121]
Is there somewhere I can see a list of all icons that are available within this repository? https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

**Comment by Potherca** [comment]
Hi! I am not entirely sure what your question is...

Do you want to know which icons are available in _this_ repository (i.e. `plantuml-stdlib/C4-PlantUML`)? In which case, C4 doesn't really provide icons, but more functionality to alter how elements are displayed by PlantUML.

Or do you want to know which icons are available in `tupadr3/plantuml-icon-font-sprites/`? In which case I don't entirely understand why you are asking here, rather than there. That said, there is an overview of available icons at: https://github.com/tupadr3/plantuml-icon-font-sprites/blob/master/dev2/index.md

**Comment by faocrates** [comment]
Thank you that overview page was what I was looking for. I could see in the examples how you can use a handful of icons based on their names but other than those I couldn't see how I could know what other icons are available.

**Comment by Potherca** [comment]
Glad I could be of help!

I'll keep an eye on https://github.com/tupadr3/plantuml-icon-font-sprites, so if you have more question,  you can ask them there and I'll be sure to supply answers as best I can. :+1:

**Comment by faocrates** [comment]
Thank you again!
