### ISSUE TITLE
Rel between entities with children

### ISSUE THREAD

**Issue by tamasperger** [plantuml-stdlib/C4-PlantUML#13]
When using Rel to connect two higher level entities (e.g. System) both having children (e.g. Container), the rendered image will display the following: "===label", instead of the formatted label.

Example:
```
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System(A, "systemA") {
    Container(B,"containerB","B")
}
System(C, "systemC") {
    Container(D,"containerD","D")
}
'This is wrong:
Rel(A,C,"AC")

'These are all OK:
'Rel(A,B,"AB")
'Rel(A,D,"AD")
'Rel(B,C,"BC")
'Rel(B,D,"BD")
'Rel(C,D,"CD")
@enduml
```

**Comment by adrianvlupu** [comment]
You are correct. It seems that replacing `"===e_label"` with `e_label` in the C4.puml file fixes the issue. I will create a pull request with this.

In the meantime you have two options. Either define your own rel
```
!define MyRel(e_alias1, e_alias2, e_label, e_direction="") e_alias1 e_direction e_alias2 : e_label
```
or make the relationship using plantuml directly
```
A --> C: This works
```

Also, I recommend using the `System_Boundary` instead of nesting Containers inside the system directly.

![enterprise](https://www.plantuml.com/plantuml/png/0/dP9TQy8m58Rl2_qFMMwcK0sENHKdjjLDGUlGojWN9RQPXiLKaXHnO_zz9zCMOLTRwCN9UzxpdEGqVMseCkLM8CoaOMgdk6ROTIwup4IPir89j35cftr25DstrzniobMfcSeAy4lJpeejcVECgho8ETinGQBhrhsWqYod4xAb6gWWfH7uAPTCjNVGpdMWHyxUG43Jmvo91akfu5HtF7IAhcmaw8e96-HSiSpmGjvWtAmidVD4NOVygl2FFGpBDlBVpLua8LtDFvYV3ADHdDxEuYHTZ9-6lUSJ-hLBRBv7YBt-97YSBPFqOPoCqidmRXWFhBeumC2sZS13MF-40PpWqtKGh7g4ZT33MRK9iOT3t7IThwew3OjIvbGT6b6DYN3p5sLmHXa0PN2YN2ORhX5yUrN8jUywTdQ15tauYAm57COwzeLwrwuJe5QhXo8V9MTYvQ525vLs_0bmDNkie4vWs07XIEupcSFx-0O0 "enterprise")

```
@startuml "enterprise"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

!define MyRel(e_alias1, e_alias2, e_label, e_direction="") e_alias1 e_direction e_alias2 : e_label
!define MyRel(e_alias1, e_alias2, e_label, e_techn, e_direction="") e_alias1 e_direction e_alias2 : e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//

LAYOUT_WITH_LEGEND

System(A, "systemA") {
    Container(B,"containerB","B")
}
System_Boundary(C, "systemC"){
    Container(D,"containerD","D")
}
'This is wrong:
Rel(A,C,"AC")

'this works
A --> C: This works

'this also works
MyRel(A, C, "Also works", "-->")

@enduml
```

**Comment by adrianvlupu** [comment]
Fixed
