### ISSUE TITLE
Make legend fill whitespace

### ISSUE THREAD

**Issue by JorisvanRoy** [plantuml-stdlib/C4-PlantUML#134]
Hi, 

Whenever I create a diagram with this plugin I like to implement the Legend with my diagrams. Whenever I add the legend to the diagrams it is put at the bottom right of the picture like this. 
![C1](https://user-images.githubusercontent.com/9107165/111295083-45ffe700-864b-11eb-98c5-e5b9c2195f64.png)

If it would be possible then it would be awesome to have the legend fill the remaining whitespace instead of creating more whitespace. Something like this:
![C1 New](https://user-images.githubusercontent.com/9107165/111295273-79db0c80-864b-11eb-8d18-d85269acec9c.png)

**Comment by Potherca** [comment]
Hi, thank you for taking the time to report this! Although I like the idea, I am not sure if this is something that can be implemented in this lib, as the placement and rendering is done by PlantUML itself.

Something _might_ be possible (with hidden lines for instance) but it will take a lot of trial and error to figuring things out.
I am not sure if any of the maintainers is willing to spend the time needed to come up with a solution for this.

Do you happen to have any ideas towards implementation yourself?

**Comment by JorisvanRoy** [comment]
Sadly i dont have much experience in PlantUML, so i dont have any insight into how this could be implemented.

**Comment by Potherca** [comment]
I've played around with this a bit and I don't think there is any way for us to improve upon the current behavior.

The only thing that I can think of to _slightly_ improve the diagram is to use `SHOW_DYNAMIC_LEGEND()` so at least the legend is smaller (as it will only show the types that are actually used in the diagram, instead of all of 'm).

The problem is that PlantUML adds the legend in a separate space by itself, at the bottom of the diagram:

| Left | center | Right |
| --- | --- | --- |
| ![left][1] | ![center][2] | ![right][3] |

There is [a post on the PlantUML forum requesting something similar](https://forum.plantuml.net/9032/legend-unnecessarily-extends-diagram-size?show=9032#q9032) but it doesn't seem to have much attention. You could try upvoting and commenting there to see if this could be implemented on the PlantUML side of things.



For now, unless you strongly disagree, I'm in favor of closing this issue, as we can't fix this in C4-PlantUML itself.

[1]: https://www.plantuml.com/plantuml/png/nLTjJzim4FwUNs71FdL2VIcK3gKHVLctINkH1XCVrcbouoEDI9tETWLbyD-N-8Zbp8Ig0XIxweVdxfuyT-VBowbKLAZrCl7aLSnNLD0bON19ruawXnirJEA8Bu4h4cP_83pBxLhGrKNCr89qMYqBNzARBo0bZU0ilWNIFchPKPyX0iv6gM0WnccI2g84vJ8p0bUk7msl8f6kETlkEqsvGg_zgLxsPGM4Yl8e0VBN8zawKo0WLPiLv64ejACjSa5PUXtpY5pIH89tRzCmgkYSocUo_5d3-faKGo7IwmUAXwHxUcaaft9H-m8bibLMPHezeQZd6luhjU5NcmJ8Ag4nrvZTGDl__j7c-FuyTwLY4mI5cd8LdglGe8TwQHGFeujNQBTYC5j6vG9OPKeh43BbcD1E6ctKqTBg7tQEHwx-rd5tr9i-Uchhqr8--ZNNn6aGt2WGd2Q_NqTLhvzlLrL_c6_ltcrKtPgSZjKlgA9rSYCLB5zQJBlTwuychfZk-7WwRbLqh6OfsAYQT6mVhTTHzKwldKUhVarMn-eNLD6xCAEdCGVnqe8Ek_t9v6Z7yQfV3VQhFYdRX-pLX8sw-NQ53Nlvhfgp-cMverQ_9izqZkmD1iCPRpPz6T_2IRiJ_9ofVF_ocpaID9ipFkE4x97oeQEIK9l6VpCFPdmm66btvCXZy56D0NEl717gY74fedXuO4HO3c0wOF9402i7W0vu_qG0U1ub1zy_VVXuVf0XSt926etivyt9GGw41R1N8CouX0XG2q0cnstoxU9h3e81lKNCW4ZJS2_H7v14nD52UNT-cBViPB-bLz1euFTbe-4tjIKWTvdJmzjcGB3AYE5ZCY2O9M8urG4n7KGOttW2KXp94W_UiosZJOX7p3BQpC0PPbELP0ANE-TOUEEBT43y7syxHyDfO9mB1vmCKnDZjufZoF2kjfsioDtOhQhkJ6RLohZOHJlD_jRBv1y0
[2]: https://www.plantuml.com/plantuml/png/nLTjJzim4FwUNs71FdL2VIcK3gKHVLctINkH1XCVrcbouoEDI9tETWLbyD-N-8Zbp8Ig0XIxweVdxfuyT-VBowbKLAZrCl7aLSnNLD0bON19ruawXnirJEA8Bu4h4cP_83pBxLhGrKNCr89qMYqBNzARBo0bZU0ilWNIFchPKPyX0iv6gM0WnccI2g84vJ8p0bUk7msl8f6kETlkEqsvGg_zgLxsPGM4Yl8e0VBN8zawKo0WLPiLv64ejACjSa5PUXtpY5pIH89tRzCmgkYSocUo_5d3-faKGo7IwmUAXwHxUcaaft9H-m8bibLMPHezeQZtdy4jjU5NcmJ8Ag4nrvZTGDl__j7c-FuyTwLY4mI5cd8LdglGe8TwQHGFeuDNQRTYC5j6vG9OPKeh43BbcD1E6YtKrTBg7tQEHwx-rd5tr9i-Uchhqr8--lNMn6qGt2WGd2Q_NqTLhvzlLrL_c6_ltcrKtPgSZjKjgB9rSYCLB5zQJBlTwuychfZk-7WwRbLqh6OfsAYQT6mVhTTHzKwlNKUhVarsn-eNLD6xCAEdCGVnqe8Ek_t9v6Z7yQfV3VQhFYdRX-pLX8sw-NQ53Nlvhfgp-cMverQ_9izqZkmD1iCPRpPz6T_2IRiJ_9ofVF_ocpaID9ipFkE4x97oeQEIK9l6VpCFPdmm66btvCXZy56D0NEl717gY74fedXuO4HO3c0wOF9402i7W0vu_qG0U1ub1zy_VVXuVf0XSt926etivyt9GGw41R1N8CouX0XG2q0cnstoxU9h3e81lKNCW4ZJS2_H7v14nD52UNT-cBViPB-bLz1euFTbe-4tjIKWTvdJmzjcGB3AYE5ZCY2O9M8urG4n7KGOttW2KXp94W_UiosZJOX7p3BQpC0PPbEHvAxf5Txu3XqG_yVRpj5m6XZdmW67mfJ3sAsw63AyeMqdAz8sTgkWkvEPCbbyLhrEix_rCla7
[3]: https://www.plantuml.com/plantuml/png/nLTjJzim4FwUNs71FdL2JLie7KeZ-h9ka_OY3IO-hDFanaSQaJgTxGhAuBylyH7BcIbL1IXsrG_FtJrvxiwNbrEfg52hHUh9guGlgQ0Bmk2Ihb9r3ZTga2OnNm1N9Ch_G7YMsxMWouk4gJbf-xw5B-ZD5v2Ind2Mt09f7Vbsr6U8WRDX9XY8KPPcWYX1kSoDm9NhHwEhM6GhphRxJZAkq6j_efTzMG6HeZnEWVprIBxE50Z8r7e9HHWARMkBd5EMNISy9fSqbU3TspICAZgZyfaiVrQmUYR5G8Zi-e7Y8UckNXefg5pKla25R9bNcSPFAEh-Pt1BRVZLEWMoJ6d2DMOtqFQ_VxGvGJ0hNAbOXs6ffbg5voeqwA5U6iN3wE2Rj5inc2sZSWviOqfB43BZcD1E6YtKrUBt3jl7GrU_VzmPTYUFdjhwj5IFVhqrSHi4Dme4f-dlrr7LxHNRLTKR5DkxTnjLjoQdOtKBsjWwkPOA5YyjfjNgzePZLqndT3mP-HiwLhCKR5HzEhQCrkkeUgVNJgDLloPtj6eMjA5tKKvF4mxYfGKTTdhZyT6EurM_6knNhLAs3Dch2HjsYkqA6tIBlMNEwfTbZLhzcZpJERBNxm-clDaCP78B9wrs-7EgYlqhQ1P8s6nE-PGJiaUgXuvAGcsQuCqidF9-VwZTaQE8mKSr1ioyQaIa8qQLYFBXWH5HDO3fWF4J0QmQ03hW_HC1u7cK77p_zE7Z-K6EpCW9QJJodpSZ1mKGbS1UYJ3Z4Y50BG2P7BVnjukl1GW6zEO90o9DmxrKVq0IaSHpvTq5KT6oatrVhx3HmE_BHYDeQaj8xdAdXxVDa62L4SF7P4WmIyHmgaDYEeWmll64f3oI5HwyPrj6cn2Fc6MqcO4ppEP5aoozyKqw9C6Fj-sZmIGqpgK3ZeOfYh5RrJ5aU5lRJbOcR-nsMNSbiufbNEogdUP_gqNw3m00

**Comment by kirchsth** [comment]
@Potherca, @JorisvanRoy: I found a workaround via note, but I cannot remove the shadow or line of the note (the text in the middle is copied from the dynamic legend definiton)

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")


skinparam note {
    backgroundcolor white
    bordercolor white
}

note left of c1 
|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
$showActiveLegendEntries($tagDefaultLegend)
$showActiveLegendEntries($tagCustomLegend)
endnote

note right of twitter
|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
$showActiveLegendEntries($tagDefaultLegend)
$showActiveLegendEntries($tagCustomLegend)
endnote
@enduml
```
![Legend in note](http://www.plantuml.com/plantuml/png/pP1FJzj04CNl-ocsQGv91BPIzOGGmZKMhMGW8gOzMcjxOg_OFzRkk1OgVFVEnWcW7decXumzx_V6R-RIet0uQCK-ILEheG7U8VR-B8wT6ADMOZTKWmTNMuDWCAgjZdibJF2SUcoKhEBqw-acj1vkybWBZ-2eLQRa4DA0Y_emdst0UMiMej7IdF1P4ghqw0HQDrkoxHCPTVdD3gOHxcbHhmdQ2jqhu9CsM_8_ZDFlTV9YXAeKVK_aBwXuqlTArWAbDJDgfPzFUBBTHBTPGHO7_4kqvZS_qw0bIjdHyx2PvsWvhTKBGlIWK8PF5gD41CTHQb3IWAU8BuUG2vn4cdF0I6Jte8xBlSLwyEIa-hqeDbkY0lIglesv1lJq2g7idDNlBOpvHsaedT3SM8J34IfHFxOkNAksoZe-TX9XKgnhmFtR3Kkyxxqmjf-cO8VSxdYzvkpvV4-SpVFiEhkzAeiVHPwLwLr-Tt-nMkNGWcbMg_DuJrtmPpRtdHsJ6kLlcDJCe9FW5tCKxHNinA1m4fR_PzF1ezL7bFv2jaD29zikH3pUwyF5lAI7GQk_)

BR Helmut

**Comment by Potherca** [comment]
That can be resolved by using `skinparam shadowing false`:
![image](https://user-images.githubusercontent.com/195757/114316526-3ff30e00-9b04-11eb-9fbb-29976eb95fcd.png)

**Comment by kirchsth** [comment]
@Potherca, @JorisvanRoy: It's not 100% perfect but very generic

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam shadowing false

skinparam note {
    backgroundcolor white
    bordercolor white
}

Container_Ext(A, "A", "t")
Person(B, "B")
System(C, "C", "t")
System_Boundary(SB0, "Sample System 0") {
Container(D, "D", "t")
}
System_Boundary(SB1, "Sample System 1") {
  Container(E, "E", "t")
}

Rel_R(A,B,"uses")
Rel_R(A,C,"uses")
Rel_D(B,C,"uses")
Rel_R(C,D,"uses")
Rel_D(B,D,"uses")
Rel_D(C,E,"uses")

note as legend1
<#white,#white>|<color:$LEGEND_TITLE_COLOR>**Legend1**</color> |
$showActiveLegendEntries($tagDefaultLegend)
$showActiveLegendEntries($tagCustomLegend)
endnote

note as legend2
<#white,#white>|<color:$LEGEND_TITLE_COLOR>**Legend2**</color> |
$showActiveLegendEntries($tagDefaultLegend)
$showActiveLegendEntries($tagCustomLegend)
endnote

note as legend3
<#white,#white>|<color:$LEGEND_TITLE_COLOR>**Legend3**</color> |
$showActiveLegendEntries($tagDefaultLegend)
$showActiveLegendEntries($tagCustomLegend)
endnote

Lay_L(C,legend1)
Lay_L(SB1,legend2)
Lay_D(D,legend3)
@enduml
```
![](http://www.plantuml.com/plantuml/png/nPBFRzCm7CNl_YjCw26fkcPjEKrLjUQ7459WKplEaPjuIJJ7ZkolAHNR_yutyTgDWZZi03dOykSzFxzOlZR0DDXMa7UDB8GjEQq1EdCLXfhjfrK3jTrPmtMX9709qqArOIUOxFTS62X5imlZ3nUtFVhwEGjRPe1hH7cCErWZkPvsVJun3utic6OjDJKhrRwH5Rrdml3NabJ0wGz2yTknug7IoigoK49fkgyRu4vHkkJwDNqYv7HSddu7VpsXtjh30Ro0t79jbFGZN4Qut1wmOkl7k8oF5iVog3-EwOE_ZIvHsRAs4vmwaLvw0LOxdUCdw4YE0Kz_Y9Zz5Z4R8YXz2KdHaxw4a0qN-GRhHnFF6cuG7ady2qdyw8niy8-ISyyvGKzw8cIuRMQeu1MNvOmitm_NEN7Jwd4vtF7LA4i_fb-I_ExJNPRcyKrsircDnvdRD1ulmy6seezaP6grNnVGVEDEJYNeXXj_1AnA-3sp0fmG_DqRMmEgFLfnwAkU5vw_fV3yFnPUlANmufyMpjWXp_2LF3-9m87XCJiqToZnasUm2CWrJhOLFm40)
BR Helmut

PS.: the problem is the white small line on the left side of "C" (I think it could be a problem of the Lay_L definition, but I found no workaround)

**Comment by kirchsth** [comment]
Hi @JorisvanRoy, @Potherca
I added MR #143, can you check it (via my [extended branch](https://github.com/kirchsth/C4-PlantUML/blob/extended/LayoutOptions.md#show_legend_upalias-hidestereotype-show_legend_down-show_legend_left-or-show_legend_right) )?
BR Helmut

**Comment by Potherca** [comment]
I like these changes a lot but as they are non-trivial (i.e. moving from the PlantUML `legend` entity to a note) I would want the opinions of @aheil  / @adrianvlupu / @RicardoNiepel / @IOrlandoni / @Crashedmind / @stawirej before merging it

**Comment by kirchsth** [comment]
Hi,
I see the changes only as an extension not as an replacement of the existing Legend calls!!!!!! 
The positioning itself is sometimes problematic therefore it cannot be an overall solution.

BR Helmut

PS.: In the meantime https://forum.plantuml.net/9032/legend-unnecessarily-extends-diagram-size?show=13621 contains a better layout (more in the right corner) based on "-[hidden]-->" therefore I plan to add an additional call which creates only the legend (SHOW_FLOATING_LEGEND() == $getLegendArea($hideStereotype)) and the (hidden) relation can be added separately too.
But I'm sure it will not work in all scenarious too

**Comment by kirchsth** [comment]
Hi @Potherca,

I think found a better solution, with the new calls "SHOW_FLOATING_LEGEND()" and "SET_FLOATING_DISTANCE()"

```
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

' New SHOW_FLOATING_LEGEND(), SET_FLOATING_DISTANCE()

!procedure $getHideStereotype($hideStereotype) 
!if ($hideStereotype=="true")
hide stereotype
!endif
!endprocedure

!procedure $getLegendTable() 
<#00000000,#00000000>|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
$showActiveLegendEntries($tagDefaultLegend)
$showActiveLegendEntries($tagCustomLegend)
!endprocedure

!procedure $getLegendArea($areaAlias, $hideStereotype) 
$getHideStereotype($hideStereotype)
rectangle $areaAlias<<legendArea>> [
$getLegendTable()
]
!endprocedure

!function $getHiddenLine($distance)
  !return '-[hidden]' + %substr('------------', 0, %intval($distance) + 1)
!endfunction

' enables that legend can be located in diagram, has to be last call in diagram
!unquoted procedure SHOW_FLOATING_LEGEND($alias="FLOATINGLEGEND", $hideStereotype="true")
$getLegendArea($alias, $hideStereotype)
!endprocedure

' PlantUML bug: lines which does "not match" with the orientation/direction of the diagram
' uses the same length therefore the method offers no direction at all.
' If a direction is required the Lay_...() methods can be used
!unquoted procedure SET_FLOATING_DISTANCE($from, $to, $distance="0")
$from $getHiddenLine($distance) $to
!endprocedure


Person(A1, "Person A1")
Container(B1, "Container B1", "techn")
System(C1, "System C1")
Container(A2, "Container A2", "techn")
System(A3, "Ext. System A3")
System(A3, "Ext. System A3")

Rel_R(A3, B1, "uses")
Rel_R(B1, C1, "calls")
Rel_D(A1, A2, "uses")
Rel_D(A1, A3, "uses")
Rel_D(A2, A3, "calls")
Rel_D(A2, C1, "calls")

SHOW_FLOATING_LEGEND()
SET_FLOATING_DISTANCE(FLOATINGLEGEND, C1, $distance=1)

SHOW_FLOATING_LEGEND(Legend2)
SET_FLOATING_DISTANCE(B1, Legend2, $distance=3)
@enduml
```

![](http://www.plantuml.com/plantuml/png/ZLLHSzeu47xthrXyT30v0e7SKuOmTGdNPePBEe6RU-Xq666liUPaAPLMfPdfZp_91eTWSeqV4kdxTh_LVYkRzuQO9bk8eCLb8coAa1Czcgl1GBDjVyCfjsjhK2TA4ahg9weO_CjraXlA1zC_pZyB9kdll-O3_E7u55C7hgOkc769kl_efOCEtE4M5f_k_rdzER-FbxTt7rVpsSVPtKtKxS5Yjdo6RsuNo_XkEekwGT1wr2h1r6g4zWRf4qznGQXHqTCZHktynRuBheKCZk7hwv2qnR0RU1nCJGGjb2dFodzrdKRDEMuSlsHhWP6hCFxjOlVqwjNavpXHGkchTjNIQdcxdCzMq_lv_SFaxAnIE3iR3yge2VmCsYPNspWX_XqhTYP9SpHHczZc1ZDcnQvmz_zZfzQGAlQXR-aariYYDdD_Oy6PwK7JnJTO7MXCYCcDG7ZM6ez5NM8oWIz1mx_WQ-ECcPMkDoNt0qvHphbq5LDkN8N4rG9eQIIh9NJEl-HboDSE_0xlZ5qRqb7d_E3fzE2Y1--ufEzC7AYu-67bqBwYlvKe_S4CKCu8gjD3mYIi4OHA664AN4BAsKQpeWSvSw6gP9aX5od40H-qhFncbK-gEpnzvzlC-tKTxl4A3Xl3gAzkOtwdPtViRWVsRoUixUOA19TeO9lp98TKkMKe5K71ACb3s7BAWN84fJbAOjwZGSerLlDHcIVhNZjW3PeICgn042WtLRx6J6aicG8fLwbBpL0Ra0gUvHY1Sw_lT6upO0S4Dw3nctNxjDIOiwTLlz-FkZirin-Ggv-UjFpqvwITQLKuoqZreBuMr-65TzTJhrz0dtFiRF0PjL4oYeSz2Airn4EdLN_veW-UghVmOHYwFM6IInUsU3A4HJJrCTKQfY_Juz6Bz7Xq8Zs-TDZi1_LXfn5V_eeC7b2i7agoFA2VeeChr2FbaVpDtiCtlabNlme-GYyRwCYZJOdHaN9m-iSWE3sybo-AbpeSul0rkUgL6RscwjlTXHpANJgvzmwqXVWF)

It is still not perfect:
a) it is relative to existing elements (not to the diagram corners)
b) PlantUML has a "bug(?)" that the long distances are only considered in the orientation/direction of the diagram layout itself (see below) therefore we cannot support all directions, and therefore I removed it completely.
c) and if somebody wants the working directions then he can use the Lay_...() calls.

```
@startuml
top to bottom direction
' not working
[S] -L-- [Left3]
[S] -R--- [Right4]
' working
[S] -U-- [Up3]
[S] -D--- [Down4]
@enduml
```

![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuIh9Br0eoLT8oYyfoSzLICaiIaqkoSpFur9NoCilKIZFByhEp4ldYWwELT3rqTLLYFP9JIinZeK81Ec2H88oqpDAJ6Avr55LXuBaGWjWQbt0Qbtoo_E0IXrIyrA0bWC0)

BR Helmut

**Comment by Potherca** [comment]
Would it be possible to use a note without adding a direction/link to an existing element?

Or use a separate element (for instance `rectangle`) instead of a `note`?

**Comment by kirchsth** [comment]
the floating area is already a separate rectangle with the name $areaAlias  (and no note anymore)

!procedure $getLegendArea($areaAlias, $hideStereotype) 
$getHideStereotype($hideStereotype)

' rectangle [
**rectangle** $areaAlias<<legendArea>> [

' generated table
$getLegendTable()

' end of rctangle ]
]
!endprocedure

**Comment by kirchsth** [comment]
@Potherca, @JorisvanRoy: I think the existing MR #143 is not the best solution, should I add the SHOW_FLOATING_LEGEND() and SET_FLOATING_DISTANCE() calls (maybe with better names)?
BR Helmut

**Comment by Potherca** [comment]
Yeah, I think so. Awesome work on this, by the way!

**Comment by kirchsth** [comment]
@Potherca: I updated my extended branch with the new implementation, readme.md, ... (Added  SHOW_FLOATING_LEGEND() and Lay_Distance()). The generated diagrams look like below (the left/right alignment is not 100% ok but I have no better solution)

Should we still merge it? If yes then I would update the description of the MR with the new implementation too

BR Helmut

http://www.plantuml.com/plantuml/uml/hP5DZzem48Rl-HLUr0D82r7LzbAfqY9WTv7ueC2MOpJ40t7hsAbd0ks_xnXI5BMgrCEURBypVjxvU226m7LfaplZSbjhL0LpHH_JDC1vS3HSrFkQCEJUCJeUvBvClvcG5yH5EdhVNrbm_3AVfVX3uXgrYDb8ai4u38CgefCxZGTvgl7aotIqN6p-muFh2dHubrQHBv2-aMZ_81bzge9XfBG4OWofnbECqStbSRdO3dUJpN8-ULMZYmPd95zY_yDjOBUkKd37saBJzD_Xht22VyLA-cupmd32FxwtkqbZxTJCT2LNxxfHkbUTKKqiPOMEt5VeAukA2s3b4BMgWjTrpYJ1DzUUFdKkg4ulkQsgInN8vyrg61bDA_6wBL2LagACOmm7o1iqYvutjjSOY8SwovHRHZTIsmeg8-3XQXhvSIpnV0QdBP82QvLiIHA9bFL7axTnCRlD6k-xUY-_ny2m1y98cfiyUF87LflFimlQMqs_nt2lVD0ObDX9sITlSfJpu4C9RBnhcxMs8fx96cqpx-kiNWX9z2XVXDXMMytMrqul1QuHDAMx2AO8spmlTzdZR3dSJXTFsMpoD5cCkxra1Z-piI46bsFNuX6TlWBUzf87USZkVm40

www.plantuml.com/plantuml/uml/LP7DQiCm48JlUWer9mTQcq9FFIMrtRJW9Y5fwT5if2KsbMGZhMZozbqra9-JPx-PmGEQ1G9FqHfP3dO4HRB1FJej6pWEaUGMx6XGtFLEcQXHTaHZU2uA3x_vlgSkxc90hmP7w2XNWor-Ug-wG5rHFZsi3JZw-cWAFB2lKJDiImv3xz3d8_zNY3NwCBWCxkNa9ELyCXNdLBPZutp9bmcVXAfp7DeU0w7D5AEJbELDLTzKg-lg6RVrWJ9aXx-vlAJhwxJOe6atQMDQey2Om3J1AkrB0sB02sEWRzacZS74HWtqZyNsRVNTlZQh-UVxSj4szQ9ULjbKD71igpuGE8MPISzngZvEnOnrjEOF

**Comment by kirchsth** [comment]
@JorisvanRoy: I think I found a solution which works in all scenarios. Can you check it and give me a feedback? You can test it in my extended branch. 

@Potherca: MR 134 is updated with the final implementation and can be merged.

==============

(In combination with [SHOW_FLOATING_LEGEND()](LayoutOptions.md#show_floating_legend)) a greater distance between an element and the
e.g. floating legend could be required that all e.g. corners of the drawing area can be reached.

* `Lay_Distance(from, to, ?distance)`: Sets the distance between `from` and `to` with down alignment (Lay_Distance(from,to,0) equals Lay_D(from, to)). The default alias of the floating legend is LEGEND().

==============

## SHOW_FLOATING_LEGEND(?alias, ?hideStereotype) and LEGEND()

`LAYOUT_WITH_LEGEND()` and SHOW_LEGEND(?hideStereotype)` adds the legend at the bottom right of the picture like below and additional whitespace is created.

Therefore a floating legend can be added via SHOW_FLOATING_LEGEND(), positioned with Lay_Distance() and existing whitespace is reused like below.

- `SHOW_FLOATING_LEGEND(?alias, ?hideStereotype): shows the legend in the drawing area
- `LEGEND()`: is the default alias of the created floating legend and can be used in Lay_Distance() call

```csharp
@startuml Compact Legend Layout Sample
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

Person(a, "Person A")
Container(b, "Container B", "techn")
System(c, "System C")
Container(d, "Container D", "techn")
Container_Ext(e, "Ext. Container E", "techn")

Rel_R(a, b, "calls")
Rel_D(b, c, "uses")
Rel_D(c, d, "uses")
Rel_R(d, e, "updates")

SHOW_FLOATING_LEGEND()
Lay_Distance(LEGEND(), e, 1)
@enduml
```

![Compact Legend Layout Sample](https://www.plantuml.com/plantuml/png/LT11JuCm50VmUpz5tQaa2Z7nv6aJS9hWjWoDnwQqBuDO2caVSVlsFhR8nedsz_x_qBnbGELnQ2rFkxPN6da11t265-hK3SXBrVOMs5tZj1qCy1gn3yz9ujLlV6Ym7geXWDUTGt0OwwvDVXglwu1raZuzxAno-FLH972akG53A5CAgyQ1ZtlwBsCxyA5pGjtpnUN8Luk8JIbHqM2wyPS5NH5qxIXKdW92ApJHvSZJMTNCgjbjTMAP7r40JUWRysiwlqspFLYv7zzOaMfbRI0TCHCacf3sS3K2CpCg4y1elL5uPbQ-RR_bQx5TVRvlrhB8r_ac4n6ZrSki2QYS1l6lv_9Zn9RW3Atj3m00 "Compact Legend Layout Sample")

**Comment by kirchsth** [comment]
@Potherca I think you can add it to release 2.3. too
