### ISSUE TITLE
PlantUML Stuck With No Responding

### ISSUE THREAD

**Issue by thiner** [plantuml-stdlib/C4-PlantUML#16]
Hi Richardo,

I was trying to use C4-PlantUML to render a C4 diagram, but the application is stuck there, and the log like below:
```
java -jar plantuml.jar /Users/x/Documents/MyTechDocs/C4PumlTest.puml -v 
(0.000 - 245 Mo) 237 Mo - PlantUML Version 1.2019.03 
(0.013 - 245 Mo) 237 Mo - GraphicsEnvironment.isHeadless() false 
(0.013 - 245 Mo) 237 Mo - Forcing resource load on OpenJdk 
(1.254 - 245 Mo) 236 Mo - Found 1 files 
(1.254 - 245 Mo) 236 Mo - Working on /Users/x/Documents/MyTechDocs/C4PumlTest.puml 
(1.265 - 245 Mo) 236 Mo - Setting current dir: . 
(1.265 - 245 Mo) 236 Mo - Setting current dir: /Users/x/Documents/MyTechDocs 
(1.268 - 245 Mo) 236 Mo - Using default charset 
(1.271 - 245 Mo) 236 Mo - Reading from C4PumlTest.puml 
(1.271 - 245 Mo) 236 Mo - Creating AParentFolderRegular /Users/x/Documents/MyTechDocs 
(1.283 - 245 Mo) 234 Mo - ImportedFiles::getAFile nameOrPath = /Users/x/Documents/Arch/C4PlantUML/C4_Container.puml 
(1.284 - 245 Mo) 234 Mo - ImportedFiles::getAFile currentDir = AParentFolderRegular::/Users/x/Documents/MyTechDocs 
(1.285 - 245 Mo) 234 Mo - Using default charset 
(1.285 - 245 Mo) 234 Mo - Reading from /Users/x/Documents/Arch/C4PlantUML/C4_Container.puml 
(1.292 - 245 Mo) 234 Mo - Using default charset 
(1.292 - 245 Mo) 234 Mo - Reading from /Users/x/Documents/Arch/C4PlantUML/C4_Container.puml 
(1.292 - 245 Mo) 234 Mo - Getting parent of AFileRegular::/Users/x/Documents/Arch/C4PlantUML/C4_Container.puml 
(1.292 - 245 Mo) 234 Mo - Creating AParentFolderRegular /Users/x/Documents/Arch/C4PlantUML 
(1.292 - 245 Mo) 234 Mo - -->The parent is AParentFolderRegular::/Users/x/Documents/Arch/C4PlantUML 
(1.293 - 245 Mo) 234 Mo - Creating AParentFolderRegular /Users/x/Documents/Arch/C4PlantUML 
(1.294 - 245 Mo) 234 Mo - Using default charset
```

And my .puml file content like below:
```
@startuml Basic Sample
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
@enduml
```

Could you please tell what's going wrong here?

**Comment by Potherca** [comment]
If I run [your code at http://www.plantuml.com/plantuml/](http://www.plantuml.com/plantuml/uml/JL3BJkim4DtdA-RcRbAfJIXYnQffX611KKHIM5PECb1BVbYUYQ8AyU_Oz55M8yzvd3DU4GlFerQm5YHxQ8Hs2fD_qlHg773q2lRCZkwBmeif_vIy7xkHqFVMC1hEUwkBMWd3sytpWdXGiYkgkyLvLNXKA0YBvU8cx7TLa0bfqESkX2P9ZPwioSIWfPb3MiOfYRrWwzDPqXo8KU_MTZI3y8UiNmRIiICSiNG6Nma0mCKvcx3R2US2ynqxA9rJiXSihKd3gle_XxAfyvU7DaWymcs-XCrR5R5IAJiHnFC8s49ljHE1eaV5CaQsasH63omrAccGGiNlKycCZs3mET42cBoYEXzthRKbf9ZtrBPrayv-IHVqQlE8JE69SNnug_zALcY6-84_)

It seems to work just fine:

![](http://www.plantuml.com/plantuml/png/JL3BJkim4DtdA-RcRbAfJIXYnQffX611KKHIM5PECb1BVbYUYQ8AyU_Oz55M8yzvd3DU4GlFerQm5YHxQ8Hs2fD_qlHg773q2lRCZkwBmeif_vIy7xkHqFVMC1hEUwkBMWd3sytpWdXGiYkgkyLvLNXKA0YBvU8cx7TLa0bfqESkX2P9ZPwioSIWfPb3MiOfYRrWwzDPqXo8KU_MTZI3y8UiNmRIiICSiNG6Nma0mCKvcx3R2US2ynqxA9rJiXSihKd3gle_XxAfyvU7DaWymcs-XCrR5R5IAJiHnFC8s49ljHE1eaV5CaQsasH63omrAccGGiNlKycCZs3mET42cBoYEXzthRKbf9ZtrBPrayv-IHVqQlE8JE69SNnug_zALcY6-84_)

I am closing this issue as can not be fixed in this repo.
