### ISSUE TITLE
How to hide custom tags in element text

### ISSUE THREAD

**Issue by MTomBosch** [plantuml-stdlib/C4-PlantUML#202]
I am using tags on elements to change the style of such elements using AddElementTag. These tags though I would not like to be visible in the diagram since the default C4 element tags are enough together with the custom legend that is then automatically created.

E.g. taking this diagram I do not want to see the "Element" and "Person" on the element shapes.

```
@startuml
title Software System - System Context

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

AddElementTag("Element", $fontColor="orange")

Person(User, "User", "", $tags="Element+Person")
System(SoftwareSystem, "Software System", "", $tags="Element")

Rel_D(User, SoftwareSystem, "Uses", $tags="Relationship")

@enduml

```

I have gone through the docs but could not find any real solution apart from completely hiding the stereotypes but then also the legend is gone.

Any advice on this use case?

**Comment by kirchsth** [comment]
Hi @MTomBosch,

you can hide all stereotypes with `HIDE_STEREOTYPE()`

```plantuml
@startuml
title Software System - System Context

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

HIDE_STEREOTYPE()

AddElementTag("Element", $fontColor="orange")

Person(User, "User", "", $tags="Element+Person")
System(SoftwareSystem, "Software System", "", $tags="Element")

Rel_D(User, SoftwareSystem, "Uses", $tags="Relationship")
@enduml
```

![](http://www.plantuml.com/plantuml/png/hL4_Q_im4DtrAVGJly6bIRnqAWHI4aCBBJM9CtGoidMn1PBEI6VIVljAsAOGEdQwf-FzuPvsWQIdqHf6cWpm4rxeAdq4Nu70ylK2zkW8Feanme4JyWQ9q7AbFRIaqJ7sJxlMZ0fuJpI4npptyhhfDFLZCmRmRJ9mj6dHveEHBeMk0ocZctp_i2xJwlpscbiPytnSROR8-7FNUZvaScVFBuUYFbN5iNYlFieYksFiIQd2W0L7bUmoCMEnulylw6YF1lrMe9Uk0n7f9VY0BZi7y2ikqX1n9Zh9BcmN_Vt4Yugfq6nfUdf6oKtrlxgam2EO-Z3dtPga_F2ZYbIPFYVqUeZI7JWLh_u6)

and if you only want to hide one concrete tag in the legend you could use `UpdateElementStyle` instead of `AddElementTag`

```plantuml
@startuml
title Software System - System Context

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

HIDE_STEREOTYPE()

UpdateElementStyle("Element", $fontColor="orange")

Person(User, "User", "", $tags="Element+Person")
System(SoftwareSystem, "Software System", "", $tags="Element")

Rel_D(User, SoftwareSystem, "Uses", $tags="Relationship")

SHOW_LEGEND()
@enduml
```

![](http://www.plantuml.com/plantuml/png/hL5DQp8n4BxdL-HTtiEMgdlfgI086ch1Ld6LqjCITqSDP3CXcSNwxpjXNGfjZptD1yz7viaiaWxKjLQG8Gkon2DTTE3c6WbQEHwQEJg23nA2q4j2UK0YR6LZ0jHaq0dnpxZQTWt8Cv6FZqKHz6LoCdJk3bs4K2S1HvCQsy9RxPBfE59ZpQ6OFumtQRL_MHMjPh_0gubdn9-hLhT3UdMnV5wegjofhLhltZSglnDYxnjDe2oqB5pIrKAUtQPi9FyVcJz7Ys6QOT3k11bpDX0YkdpFBnh9B9MCQuAJFiNfmB_lSSpeKys7kFkHAT_o_rKb6Mx1LekRtmyHNiSl5aDr-g5uDZvHo-NwhLgf9_Mwu7Ddu1fEuXC0)

BR Helmut

**Comment by MTomBosch** [comment]
I did not know that a legend can still be enabled although the HIDE_STEREOTYPE() function is used. When reading the docs I had the impression that HIDE_STEREOTYPES() immutably disables the legend as well. 

Thank you for the hint. This resolved my issue. I will close this issue then.
