### ISSUE TITLE
Container grouping text is not wrapped.

### ISSUE THREAD

**Issue by huornlmj** [plantuml-stdlib/C4-PlantUML#208]
Using C4_Deployment.puml (but assuming this will happen in the other C4_* files).

`Container(a, "Apple", "Red", "An apple is a tasty fruit to eat.  It comes in many colours.  Some people don't eat the seeds.)`
Yields: 
![image](https://user-images.githubusercontent.com/28444739/154539371-126a2d19-4203-4b4f-8a7c-ca8a13ae183a.png)
Which is nicely wrapped.

```
Container(a, "Apple", "Red", "An apple is a tasty fruit to eat.  It comes in many colours.  Some people don't eat the seeds.") {
    Container(seeds, "Seeds are inside", "Do not eat")
}
```
Yields: 
![image](https://user-images.githubusercontent.com/28444739/154539571-c6216d00-6256-48b3-9955-7db06a6297f4.png)

Which is not wrapped.

**Comment by kirchsth** [comment]
Hi @huornlmj,

PlantUML doesn't create line breaks in "packages" (=simple all elements which have sub elements).
Therefore I added to nodes (which is basically a package) a "poor man workaround".
But the poor man workaround supports only fix character counting based line breaks, which is not so good as the original algorithm and therefore I didn't add the "poor man workaround" to the containers too (which is only required in very rare case, if you have sub container with long description)

Atm you have 2 options:
- use (sub)node as group instead of package container (which could be logically even better in a deployment diagram), and change its meaning via $tags,...
- or add my "$breakDescr()" workaround explicitly to you "package" container

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

AddElementTag("PackageContainer", "gray", "black", "blue")


Node(n, " ") {
  ' you can model it at node (and maybe change with $tags the layout)
  Node(a, "Apple", "Red", "An apple is a tasty fruit to eat.  It comes in many colours.  Some people don't eat the seeds.", $tags="PackageContainer") {
    Container(seeds, "Seeds are inside", "Do not eat")
  }

  ' or add the PlantUML workaround (which is already part of node to your container call, used $NODE_DESCR_MAX_CHAR_WIDTH = 32)
  Container(a1, "Apple1", "Red", $breakDescr("An apple is a tasty fruit to eat.  It comes in many colours.  Some people don't eat the seeds.", $NODE_DESCR_MAX_CHAR_WIDTH)) {
    Container(seeds1, "Seeds1 are inside", "Do not eat")
  }
}

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/jP51QzjE4CNl-XJlRmAH8R7nlpqL0Z6MQGA94-oKz2R6seaalDeLkxCOKVhTkolZvb12JptDwWqpxyrFjrx8IUXqzbzhAXqKen7f_PVvtD5nLhVIX7tmx2fhX8tCAjlDUqqcpLnxKRhTprUVhv-JzEtnOTwH5tPHAWlkjHswDDGdWsofr5fp4bwepYVFL1sevbLSJArXDxd2f7OqfBhNiNbw19vCiopRMCMvYGecK_p8W4iCDg0YWowsD5e12Kny8oUZqD6mPrGDcPfnZ7VWGgZsa8QXASxAD0F6jHJNBljUStBSiafbQK19Gkj14F8ouCs5w28MJ383xWMH1dkq9hgP8Nvf6voFhLtKqRDD2vGrbv96HclFhFmiEenfRlwaSBeE-AtauqYCj4iLv3WQ-bQDQGiBOyVjaHBmCnl9M0TIQlGx_nWShJkGiy4evCUchPhnCksOr82UdC2-dV29JMWTgdC2LAJr5O9dXOlDKx4kY_LkjIqVbz_BrTroMxxU5oztkC6d_rE8z-IqE9DTlAEzs4VFGy6-Slc_n_nntka7f1Tdr8k_iOwqTtTFh-N3-kjwK-JJx9QD2ft-1G00)

I hope it helps

BR Helmut
