### ISSUE TITLE
$shadowing parameter of AddContainerTag no longer has any effect in current version of PlantUML Server (1.2022.4)

### ISSUE THREAD

**Issue by dannief** [plantuml-stdlib/C4-PlantUML#224]
See example below:

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <office/Servers/application_server>

AddContainerTag("webApp", $sprite="application_server", $legendText="web app container", $shadowing="true")

Container(web_app, "Web Application", "Java, Spring MVC, Tomcat 7.x", $tags="webApp")

SHOW_LEGEND()
@enduml
```

![example](https://www.plantuml.com/plantuml/png/PSv1ImCn40NW-_wA63oqiDrS145SQQb5aLQ5LdjSfibq6yWc8Pbq-_FD5beHhs_utfjf90YKEbFSQ2jDKiWEH3u-216WhrfDXxHB4ODqbj1I9Lqdl04xc4aaPVHEpEycdqFqjLgA3Y9Xo54ppmAqnL3vF_sFRh_N4iKQmn535E2zqH98Ezl4S_PK53Ebhdu3xOZtk9jvpqjs6ttGX3N_xuQhmHQjsk29wi4my9x9IzEP7q2vNjksvXGIyd5HN9T6MJHPb8nlivtzBcJ9t-089Llxa35RVSzBjd5TFhFxwZGq4xInlZoQQzUl7zjckNXPl3-FniKKhKgT-G40)

**Comment by kirchsth** [comment]
Hi @dannief 

I entered a bug in [forum](https://forum.plantuml.net/15879/skinparam-shadowing-true-not-working-anymore). 
Typically it is fast fixed (In the last months they did a lot of style changes/improvements)

I will inform you as soon it is fixed.

BR Helmut

**Comment by kirchsth** [comment]
Hi @dannief,

it is fixed by the plantuml team. With the next plantuml release it should work like before

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <office/Servers/application_server>

AddContainerTag("webAppShadow", $bgColor="red", $sprite="application_server", $legendText="with shadow", $shadowing="true")
AddContainerTag("webAppNoShadow", $bgColor="green", $sprite="application_server", $legendText="no shadow", $shadowing="false")
AddContainerTag("webApp", $sprite="application_server", $legendText="default is no shadow")

Container(web_app_with, "Web Application with shadow", "Java, Spring MVC, Tomcat 7.x", $tags="webAppShadow")
Container(web_app_no, "Web Application with shadow", "Java, Spring MVC, Tomcat 7.x", $tags="webAppNoShadow")
Container(web_app_default, "Web Application with shadow", "Java, Spring MVC, Tomcat 7.x", $tags="webApp")

SHOW_LEGEND()
@enduml
```
![](https://www.plantuml.com/plantuml/png/hP5HQ_8m58Rl-oloXU_2Gcrl1eEn3gMJZQ5kK3SlIzgSna2QXEJK-lFNRaEHEK7mBdcJyppapSGZSzWsAlWdTQLQ3cI3QFrTaZZMnKBYfYrR3wuo6a5ZN9aciOhfOMRiaIjP9jdD-6s8tXVpf64UmVLHaHcDJ6fmiJtYtvkwbXKaERWjE9ymQvMi64gZ2_-LFGJ1bFFz_8g94UsWd5gRRnWt7Ot8_r9aHXcNKWTys7lh949AVzE6KmK2D5_13bFQzMyYVW_wNaajKegk1Hh-vLwQ4tRX0FHbVcrEsskc_1dzPH8EDMiL4kd9mHS6mPuywgb5poc6EY92rr2IwG5BZbkYBspB8fBtVYt8uYEBoCeq_LLo6-y6DpBXq-DF2a_8jBckQcdEo7uwkAvnA35_VbqNyzdJRFau2eC9QDuswXC0)

Best regards
Helmut

PS.: if you test it via https://www.plantuml.com/ and it is not working, then a cached response is used. In this case please add e.g. a space in the puml code and it should work
