### ISSUE TITLE
Windows User, Problem getting CLI to work

### ISSUE THREAD

**Issue by clickwithclark** [plantuml-stdlib/C4-PlantUML#225]
![image](https://user-images.githubusercontent.com/20617584/168669314-b3efb7e7-0e05-46cf-9bff-ef19d366d05f.png)

## I also tried using the vs code extension but I see it broken
also, I am aware this is for C4 modelling specifically but I cant seem to get even the basic implementation working.
Thanks for you time

![image](https://user-images.githubusercontent.com/20617584/168669457-aab27155-1f72-44d5-8d34-a5b40167cd9d.png)

**Comment by Potherca** [comment]
Hi! Sorry to hear PlantUML is giving you trouble.

As this issue is not specific to this project but related to generic PlantMUL usage, I'm not sure how much we'll be able to help...  :disappointed: 

If I look at the CLI output, the line

> ```
>java.io.FileNotFoundException: C:\Users\clickwithclark\Desktop\c4 diagrams\sequenceDiagram.png (Access is denied)
>```

would indicate that (for whatever reason) PlantUML does not have the access rights needed to output the PNG to disk (i.e. write the `sequenceDiagram.png` file).

I am not sure how you could check which rights the CLI user has on windows, but that might be a good place to start.
You could also try running the PlantUML graphical user interface:

```sh
java -jar plantuml.jar -gui
```
and see if that _does_ work.

Whatever makes PlantUML not work might be the same thing which stops it form working in VS Code.

Beyond this, I would suggest asking for help either on the [PlantUML forum](https://forum.plantuml.net/) or by opening an [issue in the PlantUML repo](https://github.com/plantuml/plantuml/issues), or on a Q/A site like [StackOverflow](https://stackoverflow.com/).

As a temporary workaround, you could use an online PlantUML server such as https://www.plantuml.com/plantuml/ or https://www.planttext.com/ until you are able to resolve your local issue.

**Comment by clickwithclark** [comment]
I have good news, it turns out, it was the plantuml.jar that is the problem, what is weird is I downloaded it from the official website. I opened an issue on their repo explaining my findings [there.](https://github.com/plantuml/plantuml/issues/1019#issue-1239095253) Thanks a lot for your time helping!
