### ISSUE TITLE
the relation line between boundary seems a little strange

### ISSUE THREAD

**Issue by featheryus** [plantuml-stdlib/C4-PlantUML#229]
The line to the right, but starting from the left side

**Comment by featheryus** [comment]
The line to the right, but starting from the left side

**Comment by Potherca** [comment]
@featheryus Could you post an example to help illustrate what you mean?

(I moved your comment into the issue description, hope you don't mind)

**Comment by miriamgreis** [comment]
I have a similar problem. As soon as I introduce lines to a boundary, no matter what type of boundary, the diagram start looking not that nice.

So here is an example:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/36954592/187676204-7ec9af8f-a5e8-467e-834a-7333ab8cc09c.png">

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Boundary(yxz, "YXZ"){
    Container_Boundary(A, "A"){
        Component(B, "B")
        Component(C, "C")
        Component(D, "D")
        Component(E, "E")
        Rel(B, C, "references")
        Rel(B, D, "references")
    }
    Container_Ext(F, "F")
    Container_Ext(G, "G")
    Rel(A, F, "includes")
    Rel(A, G, "includes")
}

System(system, "System")
BiRel_Neighbor(system, A, "relates to")

Person(person, "Person")
Rel(person, A, "does something")

LAYOUT_WITH_LEGEND()
@enduml
```

I don't understand why the line from System to A is so strangely placed and also why F and G are not simply placed below A as it would happen if A wouldn't be a boundary.

If I remove the _Neighbor from the relation between System and A, it really doesn't look better because the lines are going to the right instead of just straight to the top of the boundary.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/36954592/187676768-4bc707b7-b61e-4f2d-91ff-b40c67546461.png">

**Comment by Potherca** [comment]
Thank you for posting an example @miriamgreis, that gives us something to work with!

Lets try to answer your questions...

### Why is the line from `System` to `A` placed as it is?

By default, PlantUML aligns things _implicitly_ (trying horizontally first and vertically second), which can give weird or undesirable results.

To change the layout, this project provides methods to set a direction _explicitly_, in the shape of (Bi)Rel_Down/Up/Left/Right.

For instance, using the provided example, we are unhappy with the layout of the relation between `System` and `A`.

So, instead of using `BiRel_Neighbor`, we can try `BiRel_Up`, `BiRel_Down`, `BiRel_Left`, or `BiRel_Right` and see which gives a better result:

| Method | Result | 
| --- | ---|
| `BiRel_Neighbor` | [![][Neighbor_png]][Neighbor_uml] |
| `BiRel_Up` | [![][Up_png]][Up_uml] |
| `BiRel_Down` | [![][Down_png]][Down_uml] |
| `BiRel_Left` | [![][Left_png]][Left_uml] |
| `BiRel_Right` | [![][Right_png]][Right_uml] |

Each of the Up/Down/Left/Right methods also has a shorthand notation, if you feel more so inclined: `BiRel_U`, `BiRel_D`, `BiRel_L`, or `BiRel_R`

### Why are F and G not placed below A?

This has to do with things somewhat beyond our control... C4-PlantUML feeds instructions to PlantUML, which uses Graphviz to create the layout. Because of how things work internally, `A` is treated differently, as it is a container. This means using the Up/Down/Left/Right suffix most likely won't make much difference.

Reversing the order in which elements are declared will sometimes help, so `Rel_Back(F, A, "includes")` could be tried...
However, `Rel_Back` does not (yet) have support for Up/Down/Left/Right, so the result might not be as good.

I could create a ticket to add Up/Down/Left/Right to the `Rel_Back` to make this problem easier to solve. :thinking: 

[Down_png]: https://www.plantuml.com/plantuml/png/RT5DJ_9040VmUpz57qubUQ0NJvxeIwacg4GXYfTcQKTeiY_DxZI2Xk_k30YAT2-RdT_yfzdkoA6ms2hf_QjrATiA_3LYuwx3q8htuQh6TRji7TZIQ0IDmzAei952SsRWi9BrCaok1bCkpUyceH8EmLAfI8ngZEPCm_Ezfos9AcBJwahORR3TVFptUukNrrx_q_Df9KQZg3NOdvw8EgAZypeD3MAYkDVla8GawPIK9EsKZ2Jx9OyW-Giyoi8RMD0bk4jFktptvpRP1eCnDOxPBoGdoG_2K_dAtFpz6kvSydFP7VzguFORwU5CviKrXOhqH16f1IaGd8-6EwPWdT51izz83sSI2fwg7AiCPPnHWEjQhpWwYHOFyrdnV3kxAIPPdjsdGTyRWQvQ9Ry0
[Down_uml]: https://www.plantuml.com/plantuml/uml/RT5DJ_9040VmUpz57qubUQ0NJvxeIwacg4GXYfTcQKTeiY_DxZI2Xk_k30YAT2-RdT_yfzdkoA6ms2hf_QjrATiA_3LYuwx3q8htuQh6TRji7TZIQ0IDmzAei952SsRWi9BrCaok1bCkpUyceH8EmLAfI8ngZEPCm_Ezfos9AcBJwahORR3TVFptUukNrrx_q_Df9KQZg3NOdvw8EgAZypeD3MAYkDVla8GawPIK9EsKZ2Jx9OyW-Giyoi8RMD0bk4jFktptvpRP1eCnDOxPBoGdoG_2K_dAtFpz6kvSydFP7VzguFORwU5CviKrXOhqH16f1IaGd8-6EwPWdT51izz83sSI2fwg7AiCPPnHWEjQhpWwYHOFyrdnV3kxAIPPdjsdGTyRWQvQ9Ry0
[Left_png]: https://www.plantuml.com/plantuml/png/RT5DJ_9040VmUpz57qubUQ0NJvxeIwacLOb252_DqewmoRuqkzC86hwxio1LfBriTdxpdyrs9nQPmLOAxnzNbMXhy3U8ZRqEGyFUnskEctRLMZ2LLWWAnvMMOIEOSfcHnLhmLPXSZMQkjBWhGiaiWg5IcMZPQEKoZPllFUr8P1dhLjNCx8BTzkE_FrY-l0w6dvvFNq97CAx0_FH4r16Tt7tTq20cYWV37ab8abv9IT9UoKYoN_88mftWHXbu0mEg0dlfQP_l_zmcss8mfSOf-QNa93d9QIfTsJL_luOzb_nSzgU_6jZ3GdhSatanfr1PT1IH6X0CmVgeNSSCZDKgQ0uBwN5FGi6kwcArfepL4d33rTf5YsZvi9YNpxVpcxB8ykm-3ORU15HDJ_q5
[Left_uml]: https://www.plantuml.com/plantuml/uml/RT5DJ_9040VmUpz57qubUQ0NJvxeIwacLOb252_DqewmoRuqkzC86hwxio1LfBriTdxpdyrs9nQPmLOAxnzNbMXhy3U8ZRqEGyFUnskEctRLMZ2LLWWAnvMMOIEOSfcHnLhmLPXSZMQkjBWhGiaiWg5IcMZPQEKoZPllFUr8P1dhLjNCx8BTzkE_FrY-l0w6dvvFNq97CAx0_FH4r16Tt7tTq20cYWV37ab8abv9IT9UoKYoN_88mftWHXbu0mEg0dlfQP_l_zmcss8mfSOf-QNa93d9QIfTsJL_luOzb_nSzgU_6jZ3GdhSatanfr1PT1IH6X0CmVgeNSSCZDKgQ0uBwN5FGi6kwcArfepL4d33rTf5YsZvi9YNpxVpcxB8ykm-3ORU15HDJ_q5
[Neighbor_png]: https://www.plantuml.com/plantuml/png/jT5DJy8m60VmUp_5vC98X5qycPYmbp5D48b252zBsHvPaxuiRHT1mtVtAGYAx6elJVlx_rlAXiPIRHl1oGMJ1MzAy2fhQtCT19g-3rRCLisoCQ0B9Ir8EoYK26fEfUlqZIqvMmRnLN_gjkRtuq1GOq7ZLXuhKIlfEZLc2GcwD_ytkW4XJnkyMkIHQcH9zSRVh3yklSxYvRNJ-oGUZXZVG9a4_PC9CH4Ut8tZh_OZfAZJQv4O9MwL12LfbHGb_IMFmDqDxYWDRw115c3EFMdpxP_Nf6lhZp0uGZ-N32L3EPoAJtRXxyzjJYKxbUtXN_NDRaBThz58nB2KJu2jggNInqI88GsSMZ2ULIuu1MsKzElTXBfVes3_kEjgfSAEKG9inUJALSVXuc4-ov_lPhVvECtIIUBto11asGZ-1G00
[Neighbor_uml]: https://www.plantuml.com/plantuml/uml/jT5DJy8m60VmUp_5vC98X5qycPYmbp5D48b252zBsHvPaxuiRHT1mtVtAGYAx6elJVlx_rlAXiPIRHl1oGMJ1MzAy2fhQtCT19g-3rRCLisoCQ0B9Ir8EoYK26fEfUlqZIqvMmRnLN_gjkRtuq1GOq7ZLXuhKIlfEZLc2GcwD_ytkW4XJnkyMkIHQcH9zSRVh3yklSxYvRNJ-oGUZXZVG9a4_PC9CH4Ut8tZh_OZfAZJQv4O9MwL12LfbHGb_IMFmDqDxYWDRw115c3EFMdpxP_Nf6lhZp0uGZ-N32L3EPoAJtRXxyzjJYKxbUtXN_NDRaBThz58nB2KJu2jggNInqI88GsSMZ2ULIuu1MsKzElTXBfVes3_kEjgfSAEKG9inUJALSVXuc4-ov_lPhVvECtIIUBto11asGZ-1G00
[Right_png]: https://www.plantuml.com/plantuml/png/RT7DJi9040VmUv-YSYg9q8idJz0FgWagGOZYfLdQ4PhiHxCxZQ3XtPq1GP7sijdvpNysknqu51OR9RshIXUoAS5V8zRkDWoj-EYlAbmtoyQ1BOn6qDWlZ0fhAJHdUWvBMIt3-AOtuTByOHmguH0ibVBOgDfepjGyttlUagWyCeqkXTq6sytdjTzPlBvrkb-UJrziD8fAW_tj6LB7yEZydOO64L7KwRP8J1AtIaAIj4fAalwHAKW-WKTPU0SBkW1twKcRx_xT9jrWCAB64Vk5P2JPGNWgNvcRV_w6EvViN7R7LmtSVY4zxCcygA9GFZqHlwK5AH2SZuOx9c2TqK6zNqWFUn8-xLZbM6aeuum2N5TwnT7nSF4qd-KlzxExV9ncwMCITBq1wB9HyXi0
[Right_uml]: https://www.plantuml.com/plantuml/uml/RT7DJi9040VmUv-YSYg9q8idJz0FgWagGOZYfLdQ4PhiHxCxZQ3XtPq1GP7sijdvpNysknqu51OR9RshIXUoAS5V8zRkDWoj-EYlAbmtoyQ1BOn6qDWlZ0fhAJHdUWvBMIt3-AOtuTByOHmguH0ibVBOgDfepjGyttlUagWyCeqkXTq6sytdjTzPlBvrkb-UJrziD8fAW_tj6LB7yEZydOO64L7KwRP8J1AtIaAIj4fAalwHAKW-WKTPU0SBkW1twKcRx_xT9jrWCAB64Vk5P2JPGNWgNvcRV_w6EvViN7R7LmtSVY4zxCcygA9GFZqHlwK5AH2SZuOx9c2TqK6zNqWFUn8-xLZbM6aeuum2N5TwnT7nSF4qd-KlzxExV9ncwMCITBq1wB9HyXi0
[Up_png]: https://www.plantuml.com/plantuml/png/RT5DJ_9040VmUpz57qubUQ0NJvxeIwacg4GXYfTcQKTeiY_DxZI2Xk_k30YAT2-RdT_yfzdkoA6ms2hf_QjrATiA_3LYuwx3q8htuQh6TRji7TZIQ0IDmzAei952SsRWi9BrCaok1bCkpUyceH8EmLAfI8ngZEPCm_Ezfos9AcBJwahORR3TVFptUukNrrx_q_Df9KQZg3NOdvw8EgAZypeD3MAYkDVla8GawPIK9EsKZ2Jx9OyW-Giyoi8RMD0bk4jFktptvpRP1eCnDOxPBoGdoG_2K_dAtFpz6kvSydFP7VzguFORwU5CviKrXOhvYI9I2r8WE1yDTqp1EgE3Ph-H7iua53nLELOPoZYZ0DUrNd5q4YqUvhFY-NPsKqooFBjFWxut0bsrIdu1
[Up_uml]: https://www.plantuml.com/plantuml/uml/RT5DJ_9040VmUpz57qubUQ0NJvxeIwacg4GXYfTcQKTeiY_DxZI2Xk_k30YAT2-RdT_yfzdkoA6ms2hf_QjrATiA_3LYuwx3q8htuQh6TRji7TZIQ0IDmzAei952SsRWi9BrCaok1bCkpUyceH8EmLAfI8ngZEPCm_Ezfos9AcBJwahORR3TVFptUukNrrx_q_Df9KQZg3NOdvw8EgAZypeD3MAYkDVla8GawPIK9EsKZ2Jx9OyW-Giyoi8RMD0bk4jFktptvpRP1eCnDOxPBoGdoG_2K_dAtFpz6kvSydFP7VzguFORwU5CviKrXOhvYI9I2r8WE1yDTqp1EgE3Ph-H7iua53nLELOPoZYZ0DUrNd5q4YqUvhFY-NPsKqooFBjFWxut0bsrIdu1

**Comment by miller79** [comment]
I have a question on this as well because I think the issue isnt' necessarily where the boxes are but how the arrows are drawn.  In the system example, I'm not sure why it would try to draw the arrow to the right vs just connecting to the left box.  This behavior seems to be only with boundaries but would be interested if there is work arounds outside of just playing with locations.

**Comment by Potherca** [comment]
Recently, work has been done on [LayoutOptions.md](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md) to try and explain things further and give guidance on how to deal with quirks like these.

@miller79 It might be of use to you to have a look at [LayoutOptions.md](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md).

**Comment by viblo** [comment]
Not sure if I can ressurect this one, or should create a new. Anyway, I was researching this problem a bit, and noticed there's a workaround suggested in the PlantUML forum. Basically you can create a sub diagram in the Boundary. It wont be possible to make relations to the inner elements, but in many cases I think that can be ok.

However, for this to work the Boundary procedure needs to put its body (the "inner" elements) within the `[ {{ }} ]` part. Is it possible to do such things? Otherwise maybe we could request it as a feature from PlantUML?

Something like this:

```
@startuml Debug
!include <C4/C4_Context>

HIDE_STEREOTYPE()

Boundary(frontend, "Frontend"){
    System(x, "X", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
    System(y, "Y", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
    ' System(z, "Z", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
    ' System(w, "W", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
}

rectangle backend [
    "Backend"
    {{
        System(a, "A", "Lorem ipsum dolor ")
        System(b, "B", "Lorem ipsum dolor")
    }}
    ]
   
System(i, "I", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.") 
System(j, "J", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.") 

Rel(x, backend, "")
Rel(y, backend, "")

Rel_R(i, backend, "")
Rel_L(j, backend, "")

footer Generated at %date("yyyy-MM-dd HH:mm")
@enduml
```
