### ISSUE TITLE
Legend text includes unexpected properties (e.g. $lineStyle) 

### ISSUE THREAD

**Issue by cc-stjm** [plantuml-stdlib/C4-PlantUML#342]
I'm generating plantUml from Structurizr CLI, using the [C4PlantUMLExporter](https://docs.structurizr.com/export/plantuml#c4plantumlexporter)

The legends are listing styling properties in text, e.g. mentioning $lineStyle - is there something I need to be doing (either within Structurizr or by tweaking the generated PlantUML afterwards) to avoid this?

Example PlantUML ([link](https://www.plantuml.com/plantuml/uml/jP5F2zD04CNl-odYwY45crJeeGg1sbhrKFz0AXx39ZjDbcvsmkw4MiJlxkwsqKgFwWIIcPTvZn_Csf6mDFQQ4Gu9OL8Z4VQ9L1OQKcWOUw9CeqS9IKSqk5TvRiKvQnLrOpqwi0qQ0aDPWtq-Q652sDoHrAhEjylvvo1z-R3FU-48h9UomM_yyzHg6npVw3-c2sN0NlFPQobt6demT11jocyzVvuygzijQhG5VofZHGsj13lfBqLuWdv4GvEwY1LKDrX5KF3OTqBYMPasZ5DGIHVj_vUerLtyeLFDoO1p1N_1Pu5mWwEHmbuYOeb7EWiBINbn1FsVgCTOZwYBUhbQBHzGe_ftU8nTEQe9CkLl4QlwDdbVc8ETHEkA1_nPyfsnNrT9_Mws4TQx_3kweEdCbKg2Qpns-FpEkxkOLkPKyC3qmrEz__Irsk_UxJw-IScE44ZNOEJOwvy0))

```
@startuml
top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("Element", $bgColor="#dddddd", $borderColor="#9a9a9a", $fontColor="#000000", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddBoundaryTag("Software System", $bgColor="#ffffff", $borderColor="#0b4884", $fontColor="#0b4884", $shadowing="", $borderStyle="Solid", $borderThickness="1")


System_Boundary("Foo_boundary", "Foo", $tags="Software System") {

Container(Foo.Bar, "Bar", $techn="", $descr="desc", $tags="Element", $link="")

}

SHOW_LEGEND(true)
@enduml
```

![jP7FIyCm5CVl-IjgzD21QoViC8N2t9nwc3zW4uybRTxQi3GfoIjpYF-xIRUEoOxgAxHvtxxtuGCPMsG6cqeIr7M0EiWqegu2BWpaABGYv4oeN3OSWXAnjZTnRDWcAWIMJTPOCBbM20gZN5TnBPdoiBv5BaKMJuVzLn-zFStZYba4uwAeTXD_JasdVkC3_v7EX0ApuvDRpcSIAWTPiYAa-](https://github.com/plantuml-stdlib/C4-PlantUML/assets/47748595/4a95adc6-2d88-4dc0-9b9a-c328b27fc8bd)

**Comment by kirchsth** [comment]
Hi @cc-stjm,

most of the problems are related to the generated source and for that I think the best would be that you create an issue  by the [C4PlantUMLExporter](https://github.com/structurizr/export)
- $borderstyle should use lowercase values "solid",... (or I would even prefer the macros SolidLine(),...)
- and if no $borderThickness="1" should not be displayed in the legend then it should not be set otherwise it is assumed it has a special meaning and therefore it is added to the legend
- (not relevant for the concrete problem, but maybe it can be changed too) 
   - instead of "top to bottom direction" it should use LAYOUT_TOP_DOWN() 
   - instead of "left to right direction" LAYOUT_LANDSCAPE(), in special LAYOUT_LANDSCAPE() offers a special implementation that the directions of the relations are correct

[![](https://www.plantuml.com/plantuml/png/pPDHJzim4CVVyobksIGI2G6J-i2aCG653QIE8hK8xQbouajhuVWY-mAhfdttdHtAofZsieVDhThuVF_pxz-x7WTMdllMPZjmWHxX4lg0GCwkWLS8mRITDOr13SRLjjSeOSMILYi7wfwCJdcvR1qnM58QUc-XyrHPR7Cf1TTMERxvFBd5Ag2_Ho-NNOhCkBiezWWc0DwZ57H07HlHDEI7cum3_DgHPv6zsZ2y7u_snwF5c1mhuz3lTMBXGvRj90-RseRXWNgheK9virG0qoJSchp7Md3Lcdg6LjMU0YYFqRs6Oe1Gjinsc3fWWegOgGLjeaxEiid9b-dDV36VNY_EfhTNHIctmudMv-8Q7S_LiiWVd_DTU5CjnsJ97-MlTLefHbwZtyJVgVYAyKPiRQ87QSLewBnXFChJyqffUZ1kATkdGZDUMpcVaJLRvUShKzyv3E4eVvkN0-CfzKuhlqwGCshu8LgVhGDZ-nosIUibx44rEZmSlO1DqRy3549fagFV7iT1qTX8o_LkRAG3mp4MHq-Rq4a_qwIc9bjSejFPVzEJYM0NPLuE3fydXFIRm3wGXwtaRO_3p3xtkV7uptiQ_jpJRE1OR22B_2FHedhSYIxkevpLKZI_ufVmBNlwhnUIkdUgl8ZaCucmNha1IcEeXJf-_IotrN9ht9rabjbtORgOtYucvv_EhyuAzZsMsJ4wtRVs1m00)](https://www.plantuml.com/plantuml/uml/pPDHJzim4CVVyobksIGI2G6J-i2aCG653QIE8hK8xQbouajhuVWY-mAhfdttdHtAofZsieVDhThuVF_pxz-x7WTMdllMPZjmWHxX4lg0GCwkWLS8mRITDOr13SRLjjSeOSMILYi7wfwCJdcvR1qnM58QUc-XyrHPR7Cf1TTMERxvFBd5Ag2_Ho-NNOhCkBiezWWc0DwZ57H07HlHDEI7cum3_DgHPv6zsZ2y7u_snwF5c1mhuz3lTMBXGvRj90-RseRXWNgheK9virG0qoJSchp7Md3Lcdg6LjMU0YYFqRs6Oe1Gjinsc3fWWegOgGLjeaxEiid9b-dDV36VNY_EfhTNHIctmudMv-8Q7S_LiiWVd_DTU5CjnsJ97-MlTLefHbwZtyJVgVYAyKPiRQ87QSLewBnXFChJyqffUZ1kATkdGZDUMpcVaJLRvUShKzyv3E4eVvkN0-CfzKuhlqwGCshu8LgVhGDZ-nosIUibx44rEZmSlO1DqRy3549fagFV7iT1qTX8o_LkRAG3mp4MHq-Rq4a_qwIc9bjSejFPVzEJYM0NPLuE3fydXFIRm3wGXwtaRO_3p3xtkV7uptiQ_jpJRE1OR22B_2FHedhSYIxkevpLKZI_ufVmBNlwhnUIkdUgl8ZaCucmNha1IcEeXJf-_IotrN9ht9rabjbtORgOtYucvv_EhyuAzZsMsJ4wtRVs1m00)
   
But independent of that I will check why $lineStyle is displayed in the legend, this should not be the case at all.

BR Helmut

**Comment by kirchsth** [comment]
Hi @cc-stjm,

in my extended branch I have a fixed version. Maybe you want to test it (use .../kirchsth/C4-PlantUML/extended... in the include)
(use !include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml)

```plantuml
@startuml
top to bottom direction

!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

AddElementTag("Element", $bgColor="#dddddd", $borderColor="#9a9a9a", $fontColor="#000000", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddBoundaryTag("Software System", $bgColor="#ffffff", $borderColor="#0b4884", $fontColor="#0b4884", $shadowing="", $borderStyle="Solid", $borderThickness="1")


System_Boundary("Foo_boundary", "Foo", $tags="Software System") {

Container(Foo.Bar, "Bar", $techn="", $descr="desc", $tags="Element", $link="")

}

SHOW_LEGEND(true)
@enduml
```


[![](https://www.plantuml.com/plantuml/png/fP5FYzim4CNl-XIksuC3hRs57BO5mtRJj3ri_u1JUZIoDB55P8sHngIXzBjtfFmX9SSTWwrvclVyWta893tDenM4KqQOTKY4OwQD1qK6dH0lZ5Dsrf0DH5DuNrLUxilUq31tSm2lq14uAXMErSvuDGGQgjNopGyh7Vty-bJ1RxxNe5biLpmiZGDVJl6VueFMQmiZ-pUoB_BJEN-TlUhw5LhqTVvIfqeQUWt-hB-JyOdwbbFFwbsgg8R96u8wJ-T1QjmRrtDx2MheOFc-GMkkuZU3KJi78TJvstmH2HznTbhwGq9iS4jxwI5h3e5W_1zrc-eMzQvRtjylRr2J-Zmy8OuSxHcoo3yXjjsfOr_ievra7-eR_4NsHuZBLWgUBH-bPnU_amlKu8vK6e9YxFYvv5rlp1gtuqbc-ijKNxx_Qf_MdzVVFXRaPrY81t2QT_uF)](https://www.plantuml.com/plantuml/uml/fP5FYzim4CNl-XIksuC3hRs57BO5mtRJj3ri_u1JUZIoDB55P8sHngIXzBjtfFmX9SSTWwrvclVyWta893tDenM4KqQOTKY4OwQD1qK6dH0lZ5Dsrf0DH5DuNrLUxilUq31tSm2lq14uAXMErSvuDGGQgjNopGyh7Vty-bJ1RxxNe5biLpmiZGDVJl6VueFMQmiZ-pUoB_BJEN-TlUhw5LhqTVvIfqeQUWt-hB-JyOdwbbFFwbsgg8R96u8wJ-T1QjmRrtDx2MheOFc-GMkkuZU3KJi78TJvstmH2HznTbhwGq9iS4jxwI5h3e5W_1zrc-eMzQvRtjylRr2J-Zmy8OuSxHcoo3yXjjsfOr_ievra7-eR_4NsHuZBLWgUBH-bPnU_amlKu8vK6e9YxFYvv5rlp1gtuqbc-ijKNxx_Qf_MdzVVFXRaPrY81t2QT_uF)

**Comment by cc-stjm** [comment]
Thanks, that works
