### ISSUE TITLE
Wrong layout: "== Base Query" <<boundary>> as Base Query

### ISSUE THREAD

**Issue by SHU-red** [plantuml-stdlib/C4-PlantUML#345]
Can someone tell me what im doing wrong using the syntax below?
The rendering isnt done properly and im not geeing errors

But the containers do not get the colors/formatting as they should

[Here you see the result](//www.plantuml.com/plantuml/png/hLJlJzim4FsUlyBh9j5e4qsXTEsqJfIc7KXeC8h6H-JQ5yV3ZJl_M5LD-z_dUD21YL4_xAfAYNFllVFp-OwrmShOfKXUyOe8Im5zdFGwazxjH5O6ymhKfoJPGwUSbSBz3QyOEi4Qq5SBQeD0m18gertAcD8JQIkArUOQitRhNrRh7NfJEBg955ADMWfelRAGYe9wkYQSuDni1A0Hcal1wRbRQATfNSAPWINo7tNYjAP_bRtK5VomNFbtpypkMLyNHUQYbRu0GBaajWdPT-6G8NI-0i8BJh3XidgAoR91Wre0YUZr-uk3HhspQcN3sdm4hZhrvhrwWeWgzH5b2gckGHiqmHg2VRjmzQIDwNFBJP3VTp6RnV91wsVEvlryFEj641UBxq22ZGtpyVjyscYd0LLW0a6-3vSVIuyOIBhrhq77NP-2CwlycVlU3SvmI1P34dM-YSqozL87pSRv-6Iuyrdc8FXFK9kmjV1H9BruPlA25eF3VaEr9QuOe8lwVWSsPmjyc4KHumgBZURwAGX8SK0ZxHwbkiJa3ZC8sZs330vtPRgHwgxfv8hYW92uptke7bgF9jKL2C_t3LJTsSydNOvr2Oz7tVqSvK0xsp6ia-HXl0QpzV5RYdubDzoKqffB9LUWpEOKC0NLJfCjLRlRFHhqijx0OHyU7O-_JTka-oBlHgtIcDM7JcUzNkypAPc0VIAz9mOpFTesqjkw0kvsb-vQGJVBdEh3ut-ju7TjepFUNnXTyfMk5-QbN2C132gQp4ylRcxFfv-dNt9NMNBirknI_040)

```
@startuml
!include <C4/C4_Container>

' Highlighting Base Query elements
' AddBoundaryTag("Base Query", $fontColor="red", $borderColor="red", $lineStyle = SolidLine())

' Item Styles
AddElementTag("Requirement", $bgColor="#ff0000")
AddElementTag("Requirement Document", $bgColor="#ff6666")

AddElementTag("Specification", $bgColor="#008000")
AddElementTag("Specification Document", $bgColor="#66b266")

AddElementTag("Input", $bgColor="#ffffff", $fontColor="#000000")
AddElementTag("Input Document", $bgColor="#dddddd", $fontColor="#000000")

AddElementTag("Test Case", $bgColor="#0000ff")
AddElementTag("Test Suite", $bgColor="#6666FF")
AddElementTag("Test Session", $bgColor="#D6DAF1")
AddElementTag("Test Object", $bgColor="#9DA7DE")

AddElementTag("Interface", $bgColor="#999999")
AddElementTag("Interface Document", $bgColor="#c1c1c1")

AddElementTag("Configuration Item", $bgColor="#f9cb9c", $fontColor="#000000")
AddElementTag("Confiugration Document", $bgColor="#FADAB9", $fontColor="#000000")

AddElementTag("Delivery", $bgColor="#ffa500")

AddElementTag("Defect", $bgColor="#bdf836")
AddElementTag("Change Order", $bgColor="#90ba30")
AddElementTag("Change Analysis", $bgColor="#ecf2df", $fontColor="#000000")
AddElementTag("Change Package", $bgColor="#d0e0e3", $fontColor="#000000")
AddElementTag("Work Item", $bgColor="#fff2cc", $fontColor="#000000")

' Line Styles
AddRelTag("Versioned", $lineStyle = DashedLine())

' Boundaried/Containers

Boundary("Base Query", "Base Query") {
WithoutPropertyHeader()
Container(11584048, "11584048", "TestContainer", $link="http://www.google.com", $tags="Delivery+Queried")
WithoutPropertyHeader()
Container(11584100, "11584100", "TestContainer", $link="http://www.google.com", $tags="Delivery+Queried")
}

' Relationships

' Show legend
SHOW_LEGEND()

@enduml
```

**Comment by kirchsth** [comment]
Hi @SHU-red,

an alias of the elements/lines/... cannot have spaces in it. With `Boundary("BaseQuery",...` it is working. 
Additional if you use $borderStyle instead of $lineStyle in the `AddBoundaryTag(...` call. I think the you have all your styles 
BR Helmut
(if you click on the image you see the source)
[![](https://www.plantuml.com/plantuml/png/hLHHRzey57tFh_37LwcWJIMqbC4qfb82QwLgtKgrFbR6ld6y6flPpX2Qzj_dkC2ewrHzs4L8ZdFlERx7D-VCMAnjkH39VrmIKL907yRTzhXxFrRIOYv1VqoIGtJ1MI7SttB9q3asWBwMeDS812n0MfECA3rNfQHOhsynQpR-vZJUeeFSWOsLK7hOq42hdRdI57HiRsRN0j0GpPJWz8fBQBPQrH4kBIoGV-dP9e_Cdkm6VfHS-sUFmpQu_-TvwgBHUg40POgKiSgU2rSPbiwMG7ZE2RPSoQSrQTgFi0KbDNoztlmuodSfbsLuDX-1heuztgi7g66bFcgHGgXRC1QDiO6WRnVkFAre-gpa5e9UNKodTVbWp3DbiruscdPgAgxdtu44ZGsoqRji4fNJWiunWI3VXoU8fzS8I3hLBy8pLZBdhDJ-plti1dSu8FC1gLC-YbOo_T84JKVPw7pmwhlCGF2VeDVXQE7JclJycSXpclTFUf7J5bWoGDUQWWvaJkVu9Asj64aireQRfqL0ycDQF-vng2-OF606mRYdaCB9Qv7kb7w8tLoU7nDIh_CXganhpwbkG7YyRw2hoNxqEk5ojawNOLF0ljLjd9G3RUzis2J9rc0VtNLhhjN3PdrWCJF3VUzjeLz9iiDeTZgd_MxQxRkgxT8X-CzebxGvtSEmKLYxVDzkhrQh8wOK4t14b1V3q-mcw4r5nO6wvaEgJffkgTpodrBzheHoqlfFmXHyQQgDMQ5MI003IPFPnVNT_TNaq-HprcmbPswhN8W_)](//www.plantuml.com/plantuml/png/hLHHRzey57tFh_37LwcWJIMqbC4qfb82QwLgtKgrFbR6ld6y6flPpX2Qzj_dkC2ewrHzs4L8ZdFlERx7D-VCMAnjkH39VrmIKL907yRTzhXxFrRIOYv1VqoIGtJ1MI7SttB9q3asWBwMeDS812n0MfECA3rNfQHOhsynQpR-vZJUeeFSWOsLK7hOq42hdRdI57HiRsRN0j0GpPJWz8fBQBPQrH4kBIoGV-dP9e_Cdkm6VfHS-sUFmpQu_-TvwgBHUg40POgKiSgU2rSPbiwMG7ZE2RPSoQSrQTgFi0KbDNoztlmuodSfbsLuDX-1heuztgi7g66bFcgHGgXRC1QDiO6WRnVkFAre-gpa5e9UNKodTVbWp3DbiruscdPgAgxdtu44ZGsoqRji4fNJWiunWI3VXoU8fzS8I3hLBy8pLZBdhDJ-plti1dSu8FC1gLC-YbOo_T84JKVPw7pmwhlCGF2VeDVXQE7JclJycSXpclTFUf7J5bWoGDUQWWvaJkVu9Asj64aireQRfqL0ycDQF-vng2-OF606mRYdaCB9Qv7kb7w8tLoU7nDIh_CXganhpwbkG7YyRw2hoNxqEk5ojawNOLF0ljLjd9G3RUzis2J9rc0VtNLhhjN3PdrWCJF3VUzjeLz9iiDeTZgd_MxQxRkgxT8X-CzebxGvtSEmKLYxVDzkhrQh8wOK4t14b1V3q-mcw4r5nO6wvaEgJffkgTpodrBzheHoqlfFmXHyQQgDMQ5MI003IPFPnVNT_TNaq-HprcmbPswhN8W_)

**Comment by SHU-red** [comment]
Thank you very much

**Comment by kirchsth** [comment]
I update the link of my last commit. now you see the source too
