### ISSUE TITLE
C4_Container diagram not rendering properly

### ISSUE THREAD

**Issue by The-Lum** [plantuml-stdlib/C4-PlantUML#346]
Hello C4-Plantuml maintainer,

Here is a issue _(observed on plantuml `V1.2024.4`)_ from:
- https://forum.plantuml.net/18850/c4_container-diagram-not-rendering-properly
- Is it normal or not?
- What is wrong?

Here is a minimal example:
```puml
@startuml

!include <C4/C4_Container>

Boundary("Base Query", "Base Query"){
  Container(aa, "666666666", "Testcontainer1", $link="www.google.com", $tags="Item1+Queried")
  Container(bb, "555555555", "Testcontainer2", $link="www.google.com", $tags="Item2+Queried")
}

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/ZP312e9048Rl-nJJKg0Kch9roX0zTGoYKn2hJhAakx2x9XAzUqeOHPV-stp_p7UOs5YkRLDNX4o4pAkcGDYap4_PELNISY5HRmb9L2CBhZk79jmWx1lK7Lt0v-JU2S3xnk6yhzTZXjq36fkFVT2JQINaDQ9jstgbKcM5NgxgWLjUceZkBDR1V90BBAZxPS-oNhWQysCF_xE77_O78HUbB6euoIDg8vI4m0kN8VCO-32xlPZZaXXbqJ_i2G00)](https://www.planttext.com/?text=ZP312e9048Rl-nJJKg0Kch9roX0zTGoYKn2hJhAakx2x9XAzUqeOHPV-stp_p7UOs5YkRLDNX4o4pAkcGDYap4_PELNISY5HRmb9L2CBhZk79jmWx1lK7Lt0v-JU2S3xnk6yhzTZXjq36fkFVT2JQINaDQ9jstgbKcM5NgxgWLjUceZkBDR1V90BBAZxPS-oNhWQysCF_xE77_O78HUbB6euoIDg8vI4m0kN8VCO-32xlPZZaXXbqJ_i2G00) 

Thanks for your analyse,

_[FYI @kirchsth]_
Regards,
Th.

**Comment by kirchsth** [comment]
Hi @The-Lum,

the problem is a copy of previous #345. 
The boundary alias has a space, without the space it works `Boundary("BaseQuery"...`  

[![(https://www.plantuml.com/plantuml/png/ZOpDIiH048Jl_HJje92WP4s8dbnPDYUFWdWIP3RJXi6PRfWVmoA-kuaXedYnRlLLzxUBIOUKlGCuiToxR0XlkdRJjS-TSDAMATm2x2MpqU5OgBsET9yf7DK5VXLSMlaEYDylXTRJVBrcldsWcFfrhoTowYo_RjKuZjKWCZYgUl4pJtg8MtMNoDVdizoIKUKl--4m2Q_M_B4t_xCtF-mV02yYYG8-yIE5Q8MnhfhBfgrQtE3PsyAA4dR49dlt2G00)](https://www.plantuml.com/plantuml/uml/ZOpDIiH048Jl_HJje92WP4s8dbnPDYUFWdWIP3RJXi6PRfWVmoA-kuaXedYnRlLLzxUBIOUKlGCuiToxR0XlkdRJjS-TSDAMATm2x2MpqU5OgBsET9yf7DK5VXLSMlaEYDylXTRJVBrcldsWcFfrhoTowYo_RjKuZjKWCZYgUl4pJtg8MtMNoDVdizoIKUKl--4m2Q_M_B4t_xCtF-mV02yYYG8-yIE5Q8MnhfhBfgrQtE3PsyAA4dR49dlt2G00)

@The-Lum: does PlantUML itself support spaces in the aliases?

BR Helmut

**Comment by The-Lum** [comment]
_Oups... Sorry for the noise..._

You are right PlantUML itself does not support space on aliases.

Duplicate of #345

Regards,
Th.

**Comment by The-Lum** [comment]
Duplicate of #345
