### ISSUE TITLE
Legend is not updated if there is include

### ISSUE THREAD

**Issue by xkrt** [plantuml-stdlib/C4-PlantUML#368]
Hi! First of all thank you for such a useful tool.

It seems legend doesn't play well with includes.

## No include example

When I have no `!include` legend is updated as expected. The code:
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddContainerTag("the-tag", $shape=EightSidedShape(), $legendText="The-tag (eight sided)")

Container(cont_no_tag, "Container no tag")
Container(cont_with_tag, "Container with the-tag", $tags="the-tag")

SHOW_LEGEND()
@enduml
```

Result:
<img width="415" alt="image" src="https://github.com/user-attachments/assets/26a9a0f7-5051-474d-b714-3247861d6796">

Please note, that there is `The-tag (eight sided)` in the legend.

## Include example

Now let's see a result with a `!include`:
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddContainerTag("the-tag", $shape=EightSidedShape(), $legendText="The-tag (eight sided)")

Container(cont_no_tag, "Container no tag")
Container(cont_with_tag, "Container with tag-1", $tags="the-tag")

!include include.puml

SHOW_LEGEND()
@enduml
```

Included file `include.puml`:
```
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(cont_included, "Included container with the-tag", $tags="the-tag")
@enduml
```

Result:
<img width="442" alt="image" src="https://github.com/user-attachments/assets/e0914e4f-361d-42d2-9cd0-112f00031578">

Please note that both containers with `$tags="the-tag"` have changed their shapes but there is no `The-tag (eight sided)` in the legend for some reason. I believe this is unexpected.

**Comment by kirchsth** [comment]
HI @xkrt,

the additional `!include include.puml` itself is not the problem (this works basically fine, ex. you see the included container)
The "problem" is that your  `!include include.puml`  contains an additional `!include ..../C4_Container.puml` and this initialises the legend (which is correct by design).

For me you have 2 options:
a) you remove the `include.puml` line in your include (and test the `include.puml` itself with another `includeWrapper.puml` which includes `!include ..../C4_Container.puml` and your `!include include.puml`)

b) change the order that your `include.puml` (which has already the `!include ..../C4_Container.puml`) replaces the  `!include ..../C4_Container.puml` from the main file.

BR Helmut

**Comment by xkrt** [comment]
@kirchsth thank you for the suggestions.

About options:

a) Although possible, it is not very convenient since in my real project I have a lot of includes (a lot of containers that I want to reuse between different diagrams)

b) It is working on my issue reproducing example but I could not manage to make it work on my real big diagram with a lot of includes for some reason 🤷‍♂️. Will try again later. And I believe this workaround could not work if all my components have to be wrapped in some `Boundary` since my code looks like `Boundary(...) { !include some.puml }`. If C4 really includes in `some.puml` then `Boundary` is just not yet included in root diagram file.

**Comment by kirchsth** [comment]
Hi @xkrt,

your problem is basically that you re-include the C4_* files and with that your tag definitions (and others) are reset.  

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddContainerTag("the-tag", $shape=EightSidedShape(), $legendText="The-tag (eight sided)")

Container(cont_no_tag, "Container no tag")
Container(cont_with_tag, "Container with tag-1", $tags="the-tag")

' directly include include.puml that no second file is required
'!include include.puml
' ---- start include.puml 
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(cont_included, "Included container with the-tag", $tags="the-tag")
' ---- end include.puml 

SHOW_LEGEND()
@enduml
```  
[![](https://www.plantuml.com/plantuml/png/jL5FI_j04BtlfvY67pI1fk47deH2fHOLwXzenMFOPiVimdOJToTKlxspDKQCNiqbavVtvisyMGQIdhg35HFZAjif14tKXlEYyF8uhmtfRjy5z5NZ21tDg-PGj5QwgCa3AMlsnUeiVuZGu-scECX0w1agLwoGng6Vjx6_k51gW7QoJXFIc9Eiandy2rgsk5YRMjFMA5JR-9rc_CTYZKxjy9KMoUv302b68eJ8p99CYA5l6iSiNLCoRGR9W8Dh85fbO-gH5_n1Zc2av__ZR5o4nJ0ikqr16OyLsJVupAn_dpO5qfAYOK2sKF1iB1C2U7pfMAV4TFARZDlc_C3f8DyR_lbjngdqTefJkUbBg4RnV1rl752_23erMaDih--VoitwQdrtcMPYoGp6tm40)](https://www.plantuml.com/plantuml/uml/jL5FI_j04BtlfvY67pI1fk47deH2fHOLwXzenMFOPiVimdOJToTKlxspDKQCNiqbavVtvisyMGQIdhg35HFZAjif14tKXlEYyF8uhmtfRjy5z5NZ21tDg-PGj5QwgCa3AMlsnUeiVuZGu-scECX0w1agLwoGng6Vjx6_k51gW7QoJXFIc9Eiandy2rgsk5YRMjFMA5JR-9rc_CTYZKxjy9KMoUv302b68eJ8p99CYA5l6iSiNLCoRGR9W8Dh85fbO-gH5_n1Zc2av__ZR5o4nJ0ikqr16OyLsJVupAn_dpO5qfAYOK2sKF1iB1C2U7pfMAV4TFARZDlc_C3f8DyR_lbjngdqTefJkUbBg4RnV1rl752_23erMaDih--VoitwQdrtcMPYoGp6tm40)

**Solution 1 - add variable based check**

You can solve it, if you set a variable (e.g. DONT_INCLUDE_C4_AGAIN) after each !include and explicit check it before an !include is executed, like below

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
%set_variable_value("DONT_INCLUDE_C4_AGAIN",1)

AddContainerTag("the-tag", $shape=EightSidedShape(), $legendText="The-tag (eight sided)")

Container(cont_no_tag, "Container no tag")
Container(cont_with_tag, "Container with tag-1", $tags="the-tag")

' directly include include.puml that no second file is required
'!include include.puml
' ---- start include.puml 
!if %not(%variable_exists("DONT_INCLUDE_C4_AGAIN"))
    !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
    %set_variable_value("DONT_INCLUDE_C4_AGAIN",1)
!endif

Container(cont_included, "Included container with the-tag", $tags="the-tag")
' ---- end include.puml 

SHOW_LEGEND()
@enduml
```

[![](https://www.plantuml.com/plantuml/png/pL7HYk9047pFLupXn0ICGRYd0q7Hu0bUF31oZs7CjCd0ECdDT5RtxxV7pGPMtVVDIpgLgkgcQcwH6spFoXj8NQXM0AiG6_ihZWs_J4g9LNjiBPYYrWWQ9qLzZXl5jTD45eMIntZvC_hheCEVRNpc5i4Gb2z9mQK6CscS_z02vY_SI7vKG8Dg8V1NkpJBD-boUrWbEMaMwyKczSVJqFCMGlGE6Iy37ok8a9V-cFsm5MzWbiYomhqK8FRkEmZfZu8IjCZWYZC_UnUm01oHMSSCVRBkVOE2fbpNET76pEznfclcLeNtr0lbyK1seAD7KtSR3NRM7qlRHan80mMgLzP5_F6-1SEmukWMMg0LWfsa8e9b1lwtf1FUQF1CHhOHFUpMtsT3glB4Xhh6ODZd3LTfqNuLU1X-j_e7rA8yFLJL7Iae_qqtikAkY2xv9rLqaP7rNM3U_lVkNxvDracw2a9lJWp2tm00)](https://www.plantuml.com/plantuml/uml/pL7HYk9047pFLupXn0ICGRYd0q7Hu0bUF31oZs7CjCd0ECdDT5RtxxV7pGPMtVVDIpgLgkgcQcwH6spFoXj8NQXM0AiG6_ihZWs_J4g9LNjiBPYYrWWQ9qLzZXl5jTD45eMIntZvC_hheCEVRNpc5i4Gb2z9mQK6CscS_z02vY_SI7vKG8Dg8V1NkpJBD-boUrWbEMaMwyKczSVJqFCMGlGE6Iy37ok8a9V-cFsm5MzWbiYomhqK8FRkEmZfZu8IjCZWYZC_UnUm01oHMSSCVRBkVOE2fbpNET76pEznfclcLeNtr0lbyK1seAD7KtSR3NRM7qlRHan80mMgLzP5_F6-1SEmukWMMg0LWfsa8e9b1lwtf1FUQF1CHhOHFUpMtsT3glB4Xhh6ODZd3LTfqNuLU1X-j_e7rA8yFLJL7Iae_qqtikAkY2xv9rLqaP7rNM3U_lVkNxvDracw2a9lJWp2tm00)


**(at the moment theoretically) Solution 2 - [!include_once](https://plantuml.com/preprocessing#393335a6fd28a804)** 

I checked it, but it looks like that PlantUML has a bug in this area, like below

```plantuml
@startuml
!include_once https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddContainerTag("the-tag", $shape=EightSidedShape(), $legendText="The-tag (eight sided)")

Container(cont_no_tag, "Container no tag")
Container(cont_with_tag, "Container with tag-1", $tags="the-tag")

' directly include include.puml that no second file is required
'!include include.puml
' ---- start include.puml 
!include_once https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(cont_included, "Included container with the-tag", $tags="the-tag")
' ---- end include.puml 

SHOW_LEGEND()
@enduml
```
[![](https://www.plantuml.com/plantuml/png/lL5DIyD04BtdLqo3q0IQ1i6JKAZKeaBzW5OyXcrsJ1QscxWxeVhldQbfnUZPN39vUM_Up9jv8EMfszbeP5nfEur5uqg4cgWDbtdkrNvQ6QgxRHVGbuqZT3GjcrtUMkL4c0NIrcppnKNs9D3p_IhVgK3e6IeMh536eP-sOX9TQNs2DgfAOgen8rN54pWBjMfnjZHLJMkZKQ_bEqdvZyKAdTxWEytYpPS04XGY166cSHf5fxw9Z5cufc3Q1E8J3gu1iKg7r3ql-8iieD2pSvcDYp0x3YjkOz36Oqds0_hWZk_3fa2r8Z4Co1OQNerbGW2FRnthT3GU_INZjXa_SBZApuR_TA11DBsdvcZk-XBAGKRV5nocr6_3jnli4grl7r-ArV9c-N2TfD6S6On_0W00)](//www.plantuml.com/plantuml/uml/lL5DIyD04BtdLqo3q0IQ1i6JKAZKeaBzW5OyXcrsJ1QscxWxeVhldQbfnUZPN39vUM_Up9jv8EMfszbeP5nfEur5uqg4cgWDbtdkrNvQ6QgxRHVGbuqZT3GjcrtUMkL4c0NIrcppnKNs9D3p_IhVgK3e6IeMh536eP-sOX9TQNs2DgfAOgen8rN54pWBjMfnjZHLJMkZKQ_bEqdvZyKAdTxWEytYpPS04XGY166cSHf5fxw9Z5cufc3Q1E8J3gu1iKg7r3ql-8iieD2pSvcDYp0x3YjkOz36Oqds0_hWZk_3fa2r8Z4Co1OQNerbGW2FRnthT3GU_INZjXa_SBZApuR_TA11DBsdvcZk-XBAGKRV5nocr6_3jnli4grl7r-ArV9c-N2TfD6S6On_0W00)
  
**(for you problem maybe the most elegant) Solution 3 - [Including Subpart - !startsub, !endsub, !includesub](https://plantuml.com/preprocessing#98ecfc06b2af9277)**

but I didn't check if it but based on the documentation following should work:
1) you define an `include.puml` like

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!startsub predefinedModule1
Container(cont_included, "Included container with the-tag", $tags="the-tag")
!endsub
@enduml
```

2) and then you can include it like 

```plantuml
...
!includesub include.puml!predefinedModule1
...
```

**Comment by kirchsth** [comment]
I entered in PlantUML forum a [!include_once loads multiple times](https://forum.plantuml.net/19329/include_once-loads-multiple-times) issue

**Comment by xkrt** [comment]
@kirchsth thank you for such a detailed explanation.

It looks like `includesub` doesn't work with multiline included statements:
```
!startsub predefinedModule1
Container( \
    cont_included, \
    "Included container with the-tag", \
    $tags="the-tag" \
)
!endsub
```
I've got some internal error on the rendering of root puml. We use multilines ` \` a lot for better readability in the real code. 

So I've settled on your first solution with conditional includes at the moment.

**Comment by kirchsth** [comment]
I’m glad that I could help.

**Comment by kirchsth** [comment]
In the meantime 3dSquare entered an issue in [forum](https://forum.plantuml.net/19390/breaking-long-lines-using-backslashes-breaks-includesub) for the `\ multilines` problem too
