### ISSUE TITLE
Direct linetype 

### ISSUE THREAD

**Issue by kusaleev** [plantuml-stdlib/C4-PlantUML#42]
Hi!

Currently, 2 types of relationships are supported (skinparam linetype):

- Standard (when elements are loosely connected and arrows **(skinparam linetype disabled)**)
-ortho (when the bend angles of the arrows are at right angles **(skinparam linetype ortho)**)

Is it possible to establish a “direct” connection style when each element is connected and the arrows do not bend?

**Comment by adrianvlupu** [comment]
Hi,
Other than actually using `skinparam linetype ortho` or `skinparam linetype polyline`, the best way I can think of is adding hidden relationships using the `Lay_U`, `Lay_D`, etc. helpers and trying to convince graphviz to draw it a certain way. (depends a lot on the complexity of the diagram though)

So instead of:
```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(customer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.")
System(banking_system, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")
System_Ext(mail_system, "E-mail system", "The internal Microsoft Exchange e-mail system.")

Rel(customer, banking_system, "Uses")
Rel(banking_system, mail_system, "Sends e-mail using")

Rel(customer, mail_system, "Sends e-mails to")
@enduml
```
rendering like this
![C4_Context Diagram Sample - bigbankplc-landscape](https://www.plantuml.com/plantuml/png/0/TL5BJy904BxtLuoSC85M4q-UKCB1H0m1EPFfTg0Rzj7ip5huzsv142GUT-PxpevOC4Yq9hlJJfbOKGm6Qf66duiYO9jljDInZ4n1UIVa95VU5dEjC5J-GrD3fXW_3MS6dIodxqKWGyXKF0uVqdmrJYJKZaBUT2xPZ09xrrUHnLiA0-WT9sZW5TrMkmsCVtQzj7o14nBy6gGcA1Dg06rA1Ss9sSq0bVBH2UUz-sonPo7RBu-AApuyaznRQX0SoTdh23mu6UDRFjinY8SlJIrej_R1ecZl04iVfOkXmxNf0D1LO75BqE3UqbMErMGdVOlQ_0QP3BityDd-CrNJXtIfprIhuDcl1IOxLQFR4D0bePFEvcGkpdXJTSd42TQX_kwkeop8LNpIZvo0j-h_Cxex9VmeZTB_VWC0 "C4_Context Diagram Sample - bigbankplc-landscape")

you could try to force drawing the entities in a rectangle shape like
```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

skinparam linetype polyline

Person(customer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.")
System(banking_system, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")
System_Ext(mail_system, "E-mail system", "The internal Microsoft Exchange e-mail system.")

Rel(customer, banking_system, "Uses")
Rel(banking_system, mail_system, "Sends e-mail using")
Rel(customer, mail_system, "Sends e-mails to")

Lay_R(customer, mail_system)
@enduml
```
![C4_Context Diagram Sample - bigbankplc-landscape](https://www.plantuml.com/plantuml/png/0/TL9BJm913BxlhwYS805M4q-ULCB1H0n1EPCo59WuZysq8-w_jmE2ukFOzdjEvfO5asJlgWiRZCihoid1LgJXcxfEk1jkh6ppCZCb4uDGaA69lfvPWsaLdomrvEhHzM3gCCXyybWdSeHCzTNWKlUBaPBG1ah3fhXK_6f3WmazEDrAsn0qqRLbgAef9OwXQp9Bz9Jwq3biqC4z1cLkOFHvw-Zn3ev8Y6kGBS5IKNtOQMHeZioo0pGcvY0yxFIgvvQ5V7TvK5pmVbIv1wsNDDF9wm3SEpaNTtooOv08RvPsOCCw9ezYOm1SnYmbXatdfdt0i0AFhzeLMqzdEHRZT-bwjEuho7XGPk2J_OjMi_jqscTYJOeSrmBZTxF5i26WxuGYNSt8VNl6NrNdJAomWlfvEu_oJ675H_tC2loaVOd_JoZFLC8yOhkO_SteLRTAq9_n0G00 "C4_Context Diagram Sample - bigbankplc-landscape")

It's more of a PlantUML issue though.

**Comment by kusaleev** [comment]
@adrianvlupu 

Thank you for your answer! 

I know this hack from C4 styles:)
I hoped, than something else can resolve my problem with lines direction. 
Okay, I will playing with layout and relations on my scheme.

**Comment by Potherca** [comment]
Closing as this issue lies in the upstream project PlantUML and can not be fixed in this repo.
