### ISSUE TITLE
Add dotted arrows for relationships

### ISSUE THREAD

**Issue by fineconstant** [plantuml-stdlib/C4-PlantUML#67]
Hello,

An option to make relationship arrows dotted would be very useful to express different types of relationships and distinguish them visually 😃 

I made a pull request with changes here #66
For now I named new elements using `_Async` suffix e.g. `Rel_Async(...)`, but maybe it is better not to suggest that these new relationships are asynchronous and normal ones are synchronous... in the end it can mean something different based the context.
Other names like `_Weak`, `_Dotted` or something entirely else are possible  - feel free to comment on this or suggest something 😄

**Comment by aheil** [comment]
C4 Model is about simplicity, ambiguity should be avoided. Annotations are essential. Adding an additional type of lines would introduce the "boxes and lines" dilemma the C4 model tries to avoid.

Examples: 

1. What are semantics of dotted lines in general? Will all developers understand the difference and will all developers interpret it the same way? 

2. In one diagram both types of lines are used but annotated differently. Will you follow the line style or the annotation. You have introduced redundancy we usually try to avoid in C4. 

3. Two types of lines might lead to the point where relationships are not annotated anymore as humans are "lazy". While this is ok to some degree, the implicit knowledge of this semantics will be lost over time for this particular diagram.

Also this would lead to the request of more lines and more colors while ending up in the root cause leading to the C4 model.

**Comment by fineconstant** [comment]
Thanks for your input.
I partially agree with you, I think that ambiguity must be avoided at all costs and annotations are essential indeed - I do not propose dropping them.

- About introducing new style of lines
  C4 already supports different kinds of lines/ relationship arrows - take a look at [Financial Risk System example](https://structurizr.com/share/31/diagrams#Context) from Structurizr. Solid and dashed lines are event mentioned in Simon Brown's book as @jikuja pointed here: https://github.com/plantuml-stdlib/C4-PlantUML/pull/66#issuecomment-703539936.

  In my opinion it is not about introducing new style to C4 model but rather making this library comply with existing standard.

- About avoiding ambiguity
  @jikuja https://github.com/plantuml-stdlib/C4-PlantUML/pull/66#issuecomment-703539936 also quoted the book:
  > Once again, ensure that any styling supplements the existing information wherever possible and that the styles you use are described on the key/legend.

  I agree, in order to make different styles of lines/ relationship arrows understandable in the same way by everyone, they must be described.

- About colours
  This option is already present, you can easily customize colours on your diagrams:
  ```
  Rel_(c1, c2, "label", "tech", "-[#cc44ff]->")
  Rel_(c3, c4, "label", "-[#cc44ff]->")
  ```

I will continue working on my PR and try to add arrow line styles to legend when there is more than one style present on the diagram. I hope that this way I can propose more comprehensive solution. 🏭 

I look forward to receiving more feedback from other people as well 😃

**Comment by FastNinja** [comment]
Having legend for dotted lines that explain what they mean ("async communication") can be a solution?
Showing Async VS Sync is actually very important for lots of systems and having the ability to add it would be great.

**Comment by kirchsth** [comment]
Atm we have 64 (!) different relation definitons, I wouldn't introduce additional Rel styles anymore.
I think the simplest solution is to add the "async communication" as part of the technology like below.
A second advantage would be that we need no special legend extensions.

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_SPRITE(person2)

Person(user, "Business User")
System(frs, "Financial Risk System")
System(ex1, "Ext1 System")
System(ex2, "Ext2 System")

Rel(user, frs, "view reports")
Rel(frs, ex1, "get data", "HTTPS")
Rel(frs, ex2, "get data", "RabbitMq, asnyc")
@enduml
```
![](http://www.plantuml.com/plantuml/png/ROt1JeD048Rl-nGh9vgqa19FdXeRJ4si9K3ZaGmmjXkN1NTcRVlsBiMaqNYRcU_x_raHWsNNQN6dJADTY_B8FD1375iuHGV5HrSxGjlqXj5mrFHTF6WmOsP1t6fLn-lxHJQUzjkNk0DYjFvKhNq2b44R3ME_A3QxjofBysBtMXLP_bocuO2MUfFCXCYkKpX-cilWqP4F4icztuEPA2x4s8NlbZnyKWPCeq3BND67dDXDmlFII-cPb_-WP4B93OaSzS_RgVvBuKbQ77hBvFc8hs3gFI3B5XW2Fs_ACYj-AyaV9OUwLhpzd4iWSscyl4BJkav_0m00)

A possible extension could be the support of an additional argument with "icon characters" e.g <&link-intact> (or sprite?), but I would prefere characters because they are typically smaller and predefined.
```
@startuml
[Actor]
[Participant]

sprite $triangle {
    00000000000
    00000F00000
    0000FBF0000
    0000FBF0000
    000F999F000
    000F999F000
    00F66666F00
    00F66666F00
    0F3333333F0
    0F3333333F0
    0FFFFFFFFF0
    00000000000
}

Actor -LEFT-> Participant: "<$triangle> - <&link-intact>\nldfjklasdfas fajkls dhfa"
@enduml
```
![](http://www.plantuml.com/plantuml/png/VP2nQiCm443t-uh3b6u2Gw7WOenRw4qTEdHpFHoMbIXM52DTff1_ZvAGE24uRxftqxshet2GxTf1yzd99hJG_AQ5xUp8Nbg0E0OhFRv8iEmNhiSTO2AVc9pkdRxecLDH53Jlz7w4vfpUpj2SNyWVxjq3d5fH_NpJdwhmflW3i_BQMg72yjLPFoZhXJkf_htJPZKuZjfmHCDfZgYNXZEeUw_J8my0)

**Comment by kirchsth** [comment]
Hi @fineconstant,
dotted arrows cannot be defined via skinparams.
With PR #130  you can change the color and add symbols.
![](http://www.plantuml.com/plantuml/png/VL9XQnGn4Fs-ls8yIctXUgkd22S8HKj0K2oLVYvfTkusN3PPCxCz3_6_EydktUhXThuaxqrcvkKbryGwSjUuueNrndKLGitSqlkoZ7gts5YkkyUEC9hW6JqlJ6ZAhOsc9gxBJs-lRftsVF_rIua_9LzX9UJ3pTxhnff5cneNjnWf-8lKPGwpUrbUpox_PfS3lHJw-vuOcmlAY_0zbaJn4kmQg8sM4R9gWft8W_FvWQrmRJqIQFZMelyiagsP2ylQEWB2yMuorUPqla-GqsLnX-xXPb1v71_nHuV4D9Ezfhqtq22Htc0Y9lLO_gyMS7QBS8x-2PtCl38k45RIwMneym5cfzd-vZx4HhjXcZID21m2FDeDPDrtW-w3czQlfIAhDg6B5cFQJdT9sJO_oB8VI2qQcyvAWSDuhAdranH93QPPLJ48F-DejTyuX5y5IBmQOyJgNwm-gkUmMgrMQXghTodK55Pl-b1JU0Z1ftf_9qTF_q685SRiP_f2QGtUxRCzew4kX2r1sCxxX-OQXmC7TrBTSNzPNAElkiRz0G00)

Can this solve your problem?
BR Helmut

**Comment by kirchsth** [comment]
@fineconstant, @Potherca: can we close this issue based on #130?

**Comment by kirchsth** [comment]
With #160 dotted lines are supported too
