### ISSUE TITLE
Syntac Error

### ISSUE THREAD

**Issue by e101814** [plantuml-stdlib/C4-PlantUML#78]
Please advice.

I using UML below which i put in my Confluence page. However, the UML didn't appear, besides give message "syntac error?" , From String Line 45 as image attached. Please help

https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

**Comment by e101814** [comment]
for you info tu, I have try in the codes in production, it showing connection timeout error but it working in my testing/development environment. Please advise on the issue

**Comment by BenEAVE** [comment]
Hi @e101814. Without being able to see the actual diagram you want to render I can't be sure, but I think you and I may have the same problem. Because you say it works in your local environment but not production, it makes me suspect that this is a change introduced in a recent version of PlantUML (as is mine).

Have you tried looking for lines that start with `LAYOUT_` (e.g. `LAYOUT_LEFT_RIGHT`) and appending empty `()` to the symbol (e.g. `LAYOUT_LEFT_RIGHT()`)?
