### ISSUE TITLE
White space issues

### ISSUE THREAD

**Issue by Bernold1** [plantuml-stdlib/C4-PlantUML#86]
I have recently started using C4-PlantUML, but I have been disapointed with a few things that tend to keep on happending. When there are multiple external systems in place the diagram tends to get "wider" causing a very funky layout. 
![image](https://user-images.githubusercontent.com/43014747/99909962-bfb24480-2ceb-11eb-83de-cd5efcf78d27.png)

Here the code for this diagram is:

```
@startuml C4_Elements
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

skinparam linetype ortho

Person(OrbitShareUser, "Orbit-Share User", "A User of the Orbit-Share web solution, with a personal UNI-Login Account")

System_Boundary(WebSolution, "Orbit-Share Web Solution"){
Container(SPA, "Single-Page-Application", "Container: Angular", "Client containing all of the websites UI functionality for teachers using their preferenced web browser")
Container(DeployedPage, "Deployed Web Server", "Container:Node.js, Express.js & Heroku CLI", "Deployed webserver")
Container(API, "REST API", "Container:Node.js & Express.js", "Allows users to access and share teaching resources")
ContainerDb(collectionDB, "Orbit-Share-Database", "Containts User, Content and Collection data into their respective collections")
}
System_Ext(UserDevice, "User's Device", "Stores the exported teaching resource(s) to the users device")
System_Ext(UniLogin, "UNI-Login Management System", "Optional Description")
System_Ext(OrbitBox, "ORBIT-Box", "A System that contains the sensors and actuators necessary to conduct a lessons experiments, can contain and view the teaching resource")


Rel(OrbitShareUser, DeployedPage, "Visits orbitshare.com", "HTTPS")
Rel(DeployedPage, SPA, "Delivers to user's browser")

Rel(SPA, API, "Makes API calls to", "HTTP")

Rel(API, collectionDB, "Reads from and writes to")
Rel(API, UserDevice, "Downloads teaching resource to")
Rel(API, UniLogin, "Authenticates user login using","SAML")
Rel(API, OrbitBox, "Exports Orbit-Box Files to")

@enduml
```

Is there any way to fix this issue with the commands that are already in place or is this a bug? I have tried using the layout options, but it was to no avail. Hope someone can help me out!

**Comment by aheil** [comment]
The layout should be based on the capabilities and limitations of GraphViz. There is also a current discussion if GraphViz should be included in PlantUML. Said that, maybe there are more possibilities to deal with GraphViz layouts when using the C4 extension.

**Comment by adrianvlupu** [comment]
Hi, sadly this has more to do with plantUML itself rather than this library. There are a couple of workarounds in place, usually I tend to mess around with **Rel_U, Rel_L, Rel_D, Rel_R** to see what works best in these scenarios. There is also a hidden relationship that can be added to help out in these cases **Lay_U, Lay_L, Lay_D, Lay_R**.

It this particular diagram case I would go with 

```plantuml
@startuml C4_Elements
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

skinparam linetype ortho

LAYOUT_LEFT_RIGHT

Person(OrbitShareUser, "Orbit-Share User", "A User of the Orbit-Share web solution, with a personal UNI-Login Account")

System_Boundary(WebSolution, "Orbit-Share Web Solution"){
    Container(SPA, "Single-Page-Application", "Container: Angular", "Client containing all of the websites UI functionality for teachers using their preferenced web browser")
    Container(DeployedPage, "Deployed Web Server", "Container:Node.js, Express.js & Heroku CLI", "Deployed webserver")
    Container(API, "REST API", "Container:Node.js & Express.js", "Allows users to access and share teaching resources")
    ContainerDb(collectionDB, "Orbit-Share-Database", "Containts User, Content and Collection data into their respective collections")
}
System_Ext(UserDevice, "User's Device", "Stores the exported teaching resource(s) to the users device")
System_Ext(UniLogin, "UNI-Login Management System", "Optional Description")
System_Ext(OrbitBox, "ORBIT-Box", "A System that contains the sensors and actuators necessary to conduct a lessons experiments, can contain and view the teaching resource")

Rel(OrbitShareUser, DeployedPage, "Visits orbitshare.com", "HTTPS")
Rel(DeployedPage, SPA, "Delivers to user's browser")

Rel(SPA, API, "Makes API calls to", "HTTP")

Rel_L(API, collectionDB, "Reads from and writes to")
Rel(API, UserDevice, "Downloads teaching resource to")
Rel(API, UniLogin, "Authenticates user login using","SAML")
Rel(API, OrbitBox, "Exports Orbit-Box Files to")

@enduml
```

that ends up looking like this

![C4_Elements](https://www.plantuml.com/plantuml/png/RLHDZnen3BtFht0vj20nq4fxsjCE7zj5Wbt4GAkUKCWOI3SaeoG3Ywh-zpe9ttHEcSJsiv-V_MGTCwxQIEW-pFiIDwYSJJu9nMLLO6Kah9qhxMExRTYkjH9kNIqgYuPhvSYqnVMcFH6ScKA_2YnHjhiFwLWovMQZOTkWH6Qn_ItzIlVpBZaneT2qIa9C4likLCaCsu2aMxSl4RHnQvqam-pNssmw7_QVf_F9uFlBD4d6QAnMzJUp42vVCuCpIgC9jN2HXXlmLpMwoy89z1BS6k7IOeSBi5fMJcZLX1tL0mpA49f9cBqEqg5U2GKPvxfIhjP8adnl7Mxc7VelcDdNV-8YFqMuWgSNE3xL6dyIeEzKSpqVPsIV2xMIc8xP2jEiB2Ln5ypfwMJw29bQLPA5MhfI4D70uoDv0vFoM1gLOuL32xC1B2l5VIWcXTl3KXjmoFYQQeFAUZzo40PAWqiqg3WMWOs5qJjFM-CctHwMKk-ny9bI6iVVM2IQRMJwdFEhBh3rspQX_q4Grj8PFiCB6lrUGNSug5q6yNd76BUmsNX0XfD-FWKw_XU2mfunGhkbf1h0wzA2qy0ufqTWgW0R6XE8y1IGawuClTxYzXPrhgN4m62lSztOjCSSMv2GBz9n5g80kt4I0bht508ASW4oqmVQ2RdqJrk4Cv1Fu-zHOFqFL_SXUxWLt5FkVxvOYFyUEdUQmeJ6uqT9eq9CtfLMjms8g0T2YkZVkC9H8kZSevmqFsAAUkqt04HJZ_bMHarH6fORKKPjNyOAH7NqXpUUT0RJbCvn2ACHfS9E-etPMrHMczWXnbt5dFzJwDj68-Rp9_kYuaGhIBeagdp9Q4HOK4tWJ1r3XYXRWRiG-euFFy8Jb7UBuqRVFmGDagNzGrP1D7wr-J9UfjDnJa5yZ6kVED0zbDJKABmgTkmyKi4hs4LTZzWxDP3EL82KtkS8SJ2U3-C4t8XnWgomi3Hw4whTcJ3qv1tp2YvNskdfdPBQEzqHSkjsba9M4OFA-PM4SPn01cM4_L5hrl9iDBpqlMXzFmZI7fOjtS6paCSSaoUaRcxaFm00 "C4_Elements")

**Comment by Bernold1** [comment]
Hi @adrianvlupu thank you for the quick response! Looks really nice like that! Is there anyway you can write about Rel_U, Rel_L, Rel_D, Rel_R in the documentation for this project? But thank you!
