### ISSUE TITLE
Layout issues (again)

### ISSUE THREAD

**Issue by Bernold1** [plantuml-stdlib/C4-PlantUML#87]
I have been trying to use Rel_U, Rel_L, Rel_D, Rel_R to get a better layout, but it is simply too difficult to use this on a larger project with little to no reference on what the different relations do. This is the code right now:

```plantuml
@startuml C4_Elements
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

' skinparam linetype ortho
skinparam minClassWidth 200

LAYOUT_TOP_DOWN


Container(SPA, "Single-Page-Application","Container: TypeScript and Angular", "A User of the Orbit-Share web solution, with a personal UNI-Login Account")


System_Boundary(AngularApp, "Angular Application"){
Component(FieldErrors, "FieldErrors Component", "Component: Angular Component", "Contains functionality to view")
Component(Home, "Home Component", "Component: Angular Component", "Contains a list of all uploaded content and collections, reused to show search results")
Component(Profile, "Profile Component", "Component: Angular Component", "A users profile containing a list of all content and collections they have uploaded and profile management")
Component(Support, "Support Component", "Component: Angular Component", "Support Page component containing a template and no other functionality")
Component(Toolbar, "Toolbar Component", "Component: Angular Component", "Toolbar containing features for navigation, search and logout")
Component(Welcome, "Welcome Component", "Component: Angular Component", "Component containing welcome page template")
Component(AuthenticationModule, "Auth Module", "Component: Angular Module", "Module which contains all components referring to authentication and authorization")
Component(Login, "Login Component", "Component: Angular Component", "Login functionality and layout")
Component(Register, "Register Component", "Component: Angular Component", "Registration functionality and layout")
Component(ContentModule, "Content Module", "Component: Angular Module", "Module which contains all components referring to content")
Component(CreateContent, "Create Content Component", "Component: Angular Component", "Component for uploading a single item")
Component(ViewContent, "View Content Component", "Component: Angular Component", "Component for viewing content uploaded to the platform")
Component(CollectionModule, "Collection Module", "Component: Angular Module", "Module which contains all components referring to Collections")
Component(CreateCollection, "Create Collection Component", "Component: Angular Component", "Component for uploading multiple items at once")
Component(SocialModule, "Social Module", "Component: Angular Component", "Module which contains all components referring to Social aspects")
Component(Comments, "Comments Component", "Component: Angular Component", "Gives the user the ability to comment on content")
Component(AuthenticationService, "Authentication Service", "Component: Angular Service", "Authenticates and Authorizes Users")
Component(CommentsService, "Comments Service", "Component: Angular Service", "Authenticates and Authorizes Users")
Component(ErrorService, "Error Service", "Component: Angular Service", "Creates Error messages for other services")
Component(ViewContentService, "Content Viewing Service", "Component: Angular Service", "Accesses endpoints to fetch content data")
Component(CreateContentService, "Content Creation Service", "Component: Angular Service", "Accesses endpoints to POST uploaded form data to server")
Component(CreateCollectionService, "Collection Creation Service", "Component: Angular Service", "Accesses endpoints to POST uploaded Collections to server")
Component(HomeService, "Home Service", "Component: Angular Service", "GET's all collection and content text data")
Component(ProfileService, "Profile Service", "Component: Angular Service", "GET's the currently logged in user's username, content and collection")
}

Container(Server, "REST API", "Container:Node.js & Express.js", "Expres.js webserver containing a RESTful API")

Rel(SPA, FieldErrors, "Shows validation errors using")
Rel(SPA, Home, "Upon authentication shows")
Rel(SPA, Toolbar, "Shows on all authorized pages")
Rel(SPA, Support, "Shows on support button press")
Rel(SPA, Welcome, "Start page routes to")
Rel(SPA, Login, "Logs in using")
Rel(SPA, Profile, "Uses have a")
Rel(SPA, Register, "Registers users with")
Rel(SPA, CreateContent, "Creates content with")
Rel(Home, ViewContent, "Views content with")
Rel(ViewContent, ContentModule, "Is Part of")
Rel(CreateContent, ContentModule, "Is Part of")
Rel(SPA, CreateCollection, "Creates content with")
Rel(SPA, CollectionModule, "Creates content with")
Rel(ViewContent, Comments, "Contains")
Rel(Comments, SocialModule, "Is Part of")
Rel(Login, AuthenticationModule, "Is Part of")
Rel(Register, AuthenticationModule, "Is Part of")
Rel(Register, AuthenticationModule, "Is Part of")
Rel(Login, AuthenticationService, "Authenticates using")
Rel(Register, AuthenticationService, "Authenticates using")
Rel(AuthenticationService, ErrorService, "Logs errors using")
Rel(Comments, CommentsService, "GET's and POST's using")
Rel(CreateContent, CreateContentService, "POST's using")
Rel(ViewContent, ViewContentService, "POST's using")
Rel(CreateCollection, CreateCollectionService, "POST's using")
Rel(Home, HomeService, "Gets content and collections using")
Rel(Profile, ProfileService, "Gets all information about users from")
Rel(CommentsService, ErrorService, "Logs errors using")
Rel(CreateContentService, ErrorService, "Logs errors using")
Rel(ViewContentService, ErrorService, "Logs errors using")
Rel(CreateCollectionService, ErrorService, "Logs errors using")
Rel(ProfileService, ErrorService, "Logs errors using")
Rel(HomeService, ErrorService, "Logs errors using")
Rel(AuthenticationService, Server, "Accesses endpoints")
Rel(CommentsService, Server, "Accesses endpoints")
Rel(CreateContentService, Server, "Accesses endpoints")
Rel(ViewContentService, Server, "Accesses endpoints")
Rel(CreateCollectionService, Server, "Accesses endpoints")
Rel(HomeService, Server, "Accesses endpoints")
@enduml
```
And this produces the following: 
![image](https://user-images.githubusercontent.com/43014747/99915477-3a875980-2d04-11eb-89c8-0e4da748233c.png)

This is completely unreadable, is there nothing you can do to fix a diagram like this. Another thing is that when converting to LaTeX none of the items are centered anymore. Hope someone can clarify once again.

**Comment by adrianvlupu** [comment]
Hi,

`Rel_U, Rel_L, Rel_D, Rel_R` mean left right up down, ex: Rel_L = Relation Left. It's an attempt to describe to graphviz what the diagram should look like. You are right about it missing from the documentation though, it will be added.

Regarding the diagram you chose, what I find weird about it is that the Components are part of the Container represented on the **same** diagram.
The idea behind the C4 model is that you have a drill-down style of diagrams.

So you should have a top level diagram representing your **system** first with people and external systems that interact with it and expand on that.

A second level **container** diagram that will include your SPA and API and maybe relevant top tier elements like people and other systems they interact with. Something like:

![C4_Elements](https://www.plantuml.com/plantuml/png/NL9DZvj03BtFht0vj5bf4z9gJtjQIf5QQJUWGBJgAPg00zCECsWyD1jL_Uyra92gNF37i_tcsK_afVDzgo5-s2SQMpIUn3jbIjrNs3iDZVSTFOQXawTLhNpJ7tf2LrhZ6RegRHjkLIbTPJSAEzHX_B3Cj3H-z_8SEjGe2SEFopN7zx5jEsk6ieud2l41wASodNIo1QqC-dE7O9rlhBWbMcLYBObULUKR-BHU2_4SVKztnRv8i_sNz7KZH8QEh5aCnEuXI4m5EpO3jgSC6CHAcHh8jkYRmV8D0cD-gHAXb0RiySWLTqBaP_BOxZ_RtbJIdHVM7PIVWjml7JoOtE3kjm3-OjP2CdstoBE8CJdtrxZCP8tBgEiqo-ELDS5zC2CVeU2tvgLJdGV9V2DJzrgEb0jcrZ8AAadDmRAqSBGE50lkPEa7yYVUmxylODx_4U7ugCKsoGk8icz3uzlqZQrmzOFWFIHldKCYTWR4LwQYaK1g3RncnXA1wpd44_xCsYHlVi4CUMKr5xrC5kGp5x55VLd6fCYL-pZauEo9Hgq7s0YOwNBHY1cFxegu96yJhwWyZR8BQ4vURe3GL4E39_xphVq5 "C4_Elements")

The **component** diagram that shows only the interaction between your SPA components and Containers different that the SPA. You can split the diagrams showcasing important aspects of your software, not everything needs to be on a single diagram and level, especially since you have relationships that describe **is part of**. I think the drop-down model will be better suited for showcasing that and don't forget there are also code diagrams for the level of detail you are trying to achieve here.

Regarding the layout issues, C4-PlantUML doesn't really decide on a layout, PlantUML does, and these kind of layout issues would happen with or without using this library. From my experience, going with concise clear diagrams helps a lot on readability rather than trying to find the best view.

Hope this helps. Take a look at https://c4model.com/ again and I'm sure you will find a better way to describe your software system.

**Comment by Bernold1** [comment]
Hi @adrianvlupu I actually already have a Context and a Container diagram, but now im missing a component diagram for my "client", should the component diagram really only contain the most essential details? There are many features in our product, where the above already cuts out quite a few things, should even more stuff not be documented in the component diagram? Thanks for the input about PlantUML, I have just never had the same issues when using PlantUML alone :)
